### ISSUE TITLE
Add option to take xres/yres into account in vipsthumbnail

### ISSUE THREAD

**Issue by heyimalex** [jcupitt/libvips#1078]
Just a thought, I have many tiffs with non-square x/y resolutions. This is apparently pretty common in faxes. Unfortunately vipsthumbnail doesn't take resolution into account when calculating the resize, so the output appears squished.

Right now I'm just calculating the target width and height and using `VIPS_SIZE_FORCE` in the call to `vips_thumbnail_image`. This is fine, but I think `vips_thumbnail_image` wont do shrink-on-load.

Just looking for feedback. I'm not great in C++ but if it sounds good I can take a crack at it, and if not I also totally understand!

**Comment by jcupitt** [comment]
The `FORCE` mode should do what you need, but as you say you will need to calculate the target size yourself in Python or whatever. 

Thumbnail doesn't look at xres/yres at all right now, so this would be quite a big change. I think my instinct would be that this is best implemented by users rather than by libvips.

You're right, `thumbnail_image` can't do shrink-on-load. Could you use plain `thumbnail` instead?

**Comment by heyimalex** [comment]
> I think my instinct would be that this is best implemented by users rather than by libvips.

Completely understand! I've got a workaround in place in any case. Thank you for this lib 🙏
