### ISSUE TITLE
Are vips_rot() and vips_similarity() equivalent?

### ISSUE THREAD

**Issue by janko-m** [jcupitt/libvips#1095]
I've created a ruby-vips wrapper method for rotating images, and I wrote it in a way that if the angel is a multiple of 90 degrees, then it calls `vips_rot()`, otherwise it calls `vips_similarity()`. The thing is, I cannot remember now why I did that.

So, my question is, if the angle you want to rotate is a multiple of 90 degrees, does it matter whether you're using `vips_rot()` or `vips_similarity()`? From the source code it doesn't seem like `vips_rot()` is calling `vips_similarity()`. Also, how does `vips_rot45()` compare to `vips_similarity()` (and `vips_rot()`) when using a multiple of 45 degrees?

Ideally, I would just like to be able to call `vips_similarity()` and not worry about whether the user passed an angle which was a multiple of 90 or 45 😛

**Comment by jcupitt** [comment]
Hello! 

No, they are not quite equivalent, you can get small displacements because of the way that they treat corner vs. centre sampling, and because of rounding in the way angles are represented. I'd just use similarity for anything that can take a fractional angle.

`rot45` is just for square matrixes. Imagine you have the matrix:

```
1 2 3
4 5 6 
7 8 9
```

rot45 will give you:

```
4 1 2
7 5 3
8 9 6
```

ie. the outer ring of numbers has moved around one place. It's useful for convolutions, not very good for images.

**Comment by janko-m** [comment]
Thanks for the quick reply.

Ok, great, then my current implementation of calling `vips_rot()` for multiples of 90 degrees and `vips_similarity()` otherwise is correct. I'll now make sure to document this above my method 😃

**Comment by jcupitt** [comment]
I think I wouldn't switch to rot for multiples of 90, it's likely to cause confusion and small differences. It would be slightly quicker though.

**Comment by janko-m** [comment]
Oh, I misunderstood then. Ok, great, then I'll then use `vips_similarity()` all the way 👍
