### ISSUE TITLE
PHP Imagick drop-in replacement

### ISSUE THREAD

**Issue by koenpunt** [jcupitt/libvips#123]
Not a real issue, but if the functionality of ImageMagick can be mimicked with libvips than a drop-in replacement for PHP's Imagick should be relatively easy I guess? 

Anyone want to try this with me?

**Comment by approached** [comment]
+1

**Comment by brusch** [comment]
+ 1

**Comment by andrefelipe** [comment]
+1

**Comment by b2bentrade** [comment]
+1

**Comment by jcupitt** [comment]
I'm not a php programmer, but I could perhaps do the C part. 

Could someone point me at a PHP extension written in C I could use as a model? I could adapt it into a simple vips binding, then maybe some php expert could build a nice binding on top of that. Once we have vips in php, an imagemagick replacement should be easy.

**Comment by jcupitt** [comment]
I've made a test binding here:

https://github.com/jcupitt/php-vips

It finds and links libvips, but doesn't actually do any processing yet. I'll try adding a few basic things.

**Comment by jcupitt** [comment]
I added some basic stuff, you can now do this:

```
<?php
	dl('vips.' . PHP_SHLIB_SUFFIX);

	$x = vips_image_new_from_file($argv[1]);
	$x = vips_invert($x);
	vips_image_write_to_file($x, $argv[2]);
?>
```

And it all seems to work. Any help very welcome.

**Comment by koenpunt** [comment]
Currently on vacation, but when I'm back I'm happy to help.

**Comment by jcupitt** [comment]
That would be great! It's mostly done and working now, the README has some notes on the things that still need sorting out. 

I made imagick and php-vips versions of the vips benchmark:

https://github.com/jcupitt/vips-bench/blob/master/imagick.php
https://github.com/jcupitt/vips-bench/blob/master/vips.php

And at least on that test on my laptop, php-vips is about 3x faster than imagick and needs 1/10th of the memory. 

Broken:

* phpDoc is not working for some reason.

Some features that other vips bindings have are not yet implemented:

* Not tried to make a proper package or namespace it yet. Does not 
  install `vips.php`.

* You can't assign to an array index to change an image band.

* In-place operations, like `circle`, are not yet supported.

* No exceptions yet.

* No logging at the moment. 

Some things will never be done:

* You can't use `()` to get a pixel value, since php does not support multiple
  arguments to `__invoke()`.

**Comment by jcupitt** [comment]
OK, it's all done, or at least it works for me. It's on packgist, so you just add `jcupitt/vips` to your `composer.json` and off you go. 

I'll do some benchmarks, write a blog post about it, and try to do some publicity, but probably what it really needs are some users to kick the tyres and polish it up.

**Comment by jcupitt** [comment]
https://packagist.org/packages/jcupitt/vips

**Comment by koenpunt** [comment]
This is great! I'm not using PHP that much lately, but I'll (hopefully) soon try to integrate this somewhere to see how it goes.

**Comment by zeroonea** [comment]
I'm running a vps with turnkey, nginx, php5-fpm, how I try your extension?

**Comment by jcupitt** [comment]
It's not ready for production, it's still alpha.

To try it, put this in your `composer.json`:

```
{
    "require": {
        "jcupitt/vips" : "@dev"
    }

}
```

Then `composer install` and you should get it. You'll need to have some other stuff too: a recent libvips, including all the dev headers, and you'll need to install the vips binary extension here:

https://github.com/jcupitt/php-vips-ext

**Comment by jcupitt** [comment]
Oh, it's php7 only, I should say.

**Comment by koenpunt** [comment]
> it's php7 only

The binary extension also?

**Comment by jcupitt** [comment]
I think the php layer would work in 5.3, probably, but the binary extension is php7-only.

They changed quite a bit of stuff to do with reference counting and the memory model for php7, so it's hard to make an extension which works correctly with both engines. It would be possible to fork the binary extension and back-port it to 5.3, but I don't plan to do that myself.

**Comment by jcupitt** [comment]
Final post!

Blog post about this:

http://libvips.blogspot.co.uk/2016/09/introducing-libvips-for-php.html

Reddit post:

https://www.reddit.com/r/programming/comments/53xyno/introducing_libvips_for_php_fast_low_memory_image/

And some tweets.
