### ISSUE TITLE
vips_affine() does not correctly unreference VipsInterpolateBilinear objects

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#217]
When using vips_affine(), the leak cecker reports undestroyed VipsInterpolateBilinear objects, one for each call to vips_affine(). 
The images themself are unreferenced and destroyed correctly (i.e. I do not have any undestroyed  VipsImage objects at the end of the execution), therefore I'm quite sure that the reference counting handling is correct.

I can provide additional debugging info if needed.

**Comment by jcupitt** [comment]
Oh argh, you're right:

```bash
$ vips similarity k2.jpg x.jpg --angle 45
1 objects alive:
0) VipsInterpolateBilinear (0x1a71c50), count=1
VipsInterpolateBilinear (bilinear), bilinear interpolation 
memory: high-water mark 14.04 MB
```

Stupid thing, I'll fix it.

**Comment by jcupitt** [comment]
Seems fixed now, sorry about that, brain fart a month ago.

**Comment by aferrero2707** [comment]
Thanks!

**Comment by jcupitt** [comment]
Seems fixed, I'll close. Thanks for pointing this dumbness out.

**Comment by aferrero2707** [comment]
I confirm that the issue is solved when using vips_affine() directly. However, I still get undestroyed VipsInterpolateBicubic objects when using vips_resize() with the default interpolator. 

I do not consider this a critical or urgent issue for the moment...

**Comment by jcupitt** [comment]
Oh honestly, I'm so dumb. Thanks again!

**Comment by aferrero2707** [comment]
No problem, you are welcome!

A bit out-of-topic question: do you consider vips_resize() the best available choice for digital photo resizing? Or is there still room for improvements? Also, which interpolators do you suggest to use for highest-quality upscaling and downscaling (I'm planning to use bicubic or even bilinear for real-time online preview)?

Thanks!

**Comment by jcupitt** [comment]
Oh that's a huge question. I think vips_resize() is a nice compromise between speed and accuracy. It's roughly equivalent to lanczos2, but much faster, since it reuses intermediate results between pixels. 

I think the "gold standard" is calculating a large mask for every output pixel. For example, for a 20x shrink, you'd need a 40x40 convolution mask calculated for each pixel. The mask would be roughly a sinc function, tuned to balance sharpness and aliasing. Plus perhaps some non-linear pass to tweak it for image edges. 

Nicolas Robidoux has been researching this for years, he posts a lot on the IM forums. Google some of his posts on the subject.

**Comment by aferrero2707** [comment]
I see that VIPS included the "nohalo" interpolator from Nicolas (+ others including you, it seems). Is that a good choice for shrinking and/or enlarging? Would it be better in this case to directly use vips_affine() for shrinking?

Thanks!

**Comment by jcupitt** [comment]
You can only use affine + nohalo for shrink factors between about 1.5 and 2.5, or you'll get aliasing or undersampling artefacts. Same for bicubic: there's only a very small range they work well over. 

I think I would do a simple nearest-neighbour subsample to throw something on the screen quickly, then do a vips_resize() in the background to generate the high-quality version.

Are you still using pyramids? That could make it a lot quicker, of course, and avoid the huge averaging you'd need otherwise. You could experiment with taking the layer two layers down and running bicubic on that.

**Comment by jcupitt** [comment]
Actually, go two layers down, blur, resample with bicubic, then sharpen. That's the vips_resize() algorithm, it should work well with a pyramid.

**Comment by aferrero2707** [comment]
So, if I understand correctly, the suggested shrinking procedure would be to use a simple nearest-neighbour subsample + small blur until the residual shrinking S is smaller than 2, then use vips_affine() with "nohalo" if S>1.5.

 Few more questions:
- What would you suggest for S<1.5? 
- Is "nohalo" approriate for up-sampling?
- What is the best way to do the initial nearest-neighbour subsampling? I can either chain several 2x shrinks or do a single shrink... Also, would you recommend to sharpen the subsampled image at the final step?


I'm actually still using image pyramids: anything which is read from disk (either an input file or a cached buffer) gets shrunk in 2x steps to generate the initial data that is used when the preview zoom factor is smaller than 1:1. At each 2x step, I use a simple nearest-neighbour subsampling followed by a gaussian blur with 0.7 pixels of radius. So I can definitely use the closest pyramid level when generating the preview of a scaled image.


Actually, my concern is not really the preview image (for which I can accept some approximations) but more the high-quality output that has to be generated when saving the full resolution composite image to disk.
For example, when preparing an image for printing one might want to up- or down-sample it to the native printer resolution (typically 300ppi) to avoid additional re-sampling by the printer driver...

**Comment by jcupitt** [comment]
Ah, I misunderstood. For final output I would use vips_resize(). You can always swap it for something fancier later, though I think the quality is probably OK, myself.

**Comment by aferrero2707** [comment]
I've searched through the various recent posts by Nicolas about his research on image resizing, but I have to admit that it is difficult for me to follow all the discussions in my limited spare time... are you still in contact with him? In your opinion, would there be a chance to have his newest resizing methods included in VIPS? As far as I understood, he considers the "nohalo" family of interpolators kind of obsolete...

In any case, I'll stick to vips_resize() and nohalo for the moment.

**Comment by jcupitt** [comment]
He does post a lot. Yes, I'm still in contact with him, as far as I understand, vips is still approved of, he doesn't yet have anything dramatically better.
