### ISSUE TITLE
--disable-cxx is broken

### ISSUE THREAD

**Issue by vriera** [jcupitt/libvips#231]
Trying to build libvips using a compiler without C++ support and passing the '--disable-cxx' option to the configure script is not enough to build it successfully. It doesn't build the shared library and then it fails with an error message like this one:

error: ../libvips/.libs/libvips.so: No such file or directory

**Comment by jcupitt** [comment]
Oh dear, yes, this switch has become slowly harder to support. I'll see if I can improve it.

**Comment by jcupitt** [comment]
I've spent some time looking into this and I'm not sure it can be fixed, unfortunately.

The problem seems to be in automake, as far as I can tell.

automake generates Makefile.in from Makefile.am before configure runs, so at that point it doesn't know what has been detected and what has not been detected. It sees C++ sources being referenced, even though those sources are inside conditionals, and generates a C++ link line. This then fails at build time (of course).

To see this in action, look at libvips/Makefile.am and note that all C++ sources referenced are inside conditionals. Remove Makefile.in and rerun bootstrap.sh. You'll see Makefile.in now has a line like:

```
libvips_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
```

I'm not sure how to fix this. I suppose we need to versions of every Makefile.am, one with and one without C++ support, and we need to swap them at bootstrap time.

I'm not sure this is worth it myself. I did have a user a few years ago who ran vips on embedded systems and wanted to be able to drop C++, but I don't know if that's still important. 

I'm inclined to remove this flag. What do you think?

**Comment by vriera** [comment]
I'm perfectly fine with you removing that flag :-)

**Comment by jcupitt** [comment]
OK, I've removed the --disable-cxx option. I've tested a linux and a windows build and it all seems to link OK.

Thanks for reporting this!
