### ISSUE TITLE
No way to dzsave with extension-less input image? (+ segfault)

### ISSUE THREAD

**Issue by aseemk** [jcupitt/libvips#242]
Hi there,

Fantastic work on VIPS and `dzsave`. I'm relatively new to it, but blown away by the performance. =)

It doesn't seem possible to `dzsave` with an extension-less input image, e.g. just **`foo`** instead of **`foo.jpg`** or similar, assuming I want the output to be **`foo.dzi`** still.

—

**`vips dzsave foo foo.dzi`** creates a nested `foo.dzi/foo.dzi` (and `foo.dzi/foo_files`), and outputs these errors:

```
VipsRegion: valid clipped to nothing
rename: unable to rename file "./foo/foo.dzi" as "./foo.dzi", Not a directory
```

—

**`vips dzsave foo .`** creates only a naked `_files` directory, along with these errors:

```
VipsRegion: valid clipped to nothing
rmdir: unable to remove directory "./", Invalid argument
```

—

**`vips dzsave foo foo`** segfaults:

```
** (vips:84469): CRITICAL **: gsf_outfile_new_child_full: assertion 'outfile != NULL' failed

** (vips:84469): CRITICAL **: gsf_outfile_new_child_full: assertion 'outfile != NULL' failed

** (vips:84469): CRITICAL **: gsf_output_write: assertion 'output != NULL' failed

** (vips:84469): CRITICAL **: gsf_output_close: assertion 'GSF_IS_OUTPUT (output)' failed

** (vips:84469): CRITICAL **: gsf_output_set_error: assertion 'GSF_IS_OUTPUT (output)' failed

(vips:84469): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (vips:84469): CRITICAL **: gsf_output_error: assertion 'GSF_IS_OUTPUT (output)' failed
Segmentation fault: 11
```

—

I figured out that if I manually add an extension to my input file, e.g. **`foo.jpg`**, then...

**`vips dzsave foo.jpg foo`** works: creates `foo.dzi` and `foo_files`.

—

Not a big deal, and easy to work around, but thought I'd file: it'd be nice if an extension-less input file could be used, to create a sibling `.dzi` file with the same basename.

Thanks, and keep up the great work!

**Comment by jcupitt** [comment]
Hi @aseemk, this is expected behaviour, I think, just with unhelpful error messages. 

dzsave uses libgsf for output. This lets it create zip files directly -- you can write:

```
vips dzsave foo foo.zip
```

and it'll write a zipfile called `foo.zip` containing:

```
Archive:  foo.zip
 extracting: foo/foo_files/11/0_0.jpeg  
... snip
 extracting: foo/foo_files/0/0_0.jpeg  
 extracting: foo/foo.dzi 
```

This is important on Windows where the filesystem is very slow. You get a significant speedup by writing a zipfile instead. 

If you output to the filesystem, libgsf will not create files within an existing directory, it can only write subdirectories. So your command:

```
vips dzsave foo foo.dzi
```

will first create a directory called `foo.dzi` and write `foo.dzi/foo_files/..` and `foo.dzi/foo.dzi`, then after processing, rename `foo.dzi/foo_files` as `foo_files` and `foo.dzi/foo.dzi` as `foo.dzi`. This last rename will fail as (obviously) the directory `foo.dzi` already exists.  This then causes the unhelpful message you saw.

I suppose a solution would be to create a temporary directory called something like `foo-temp-767665` for the output files. I'll add a note to TODO.

The command:

```
vips dzsave foo foo
```

will delete its own input before running, which obviously kills everything. You'll find  that:

```
vips copy foo.jpg foo.jpg
```

will segv as well. 

I suppose a temporary output directory would fix that too, though obviously it wouldn't help the general case.

**Comment by jcupitt** [comment]
I've made it create a unique temp dir in the current directory, so this now works:

```
vips dzsave foo foo
```

Thanks for the suggestion.

**Comment by jcupitt** [comment]
... the temp dir is now named something like `foo-KJHGT`, so at least it won't get lost. 

I'll close the issue, please reopen if it's not working.
