### ISSUE TITLE
Does Vips supports RAW files like NEF,CR2 files

### ISSUE THREAD

**Issue by shilpi230** [jcupitt/libvips#255]
I have some RAW images from different cameras like NEF from nikon CR2 etc from canon. Does vips supports the compression of this files if yes then what is the command. I tried this `vips pngsave DSC_0037.NEF test.png`  I got this error `vips warning: TIFFReadDirectory: Unknown field with tag 36867 (0x9003) encountered`

**Comment by jcupitt** [comment]
vips does not directly support NEF and CR2, but it does support loading of any format that ImageMagick supports, via `magickload`. Normally this is automatic, but in this case because Nikon are using a TIFF container, vips is trying to open it with libtiff rather than libMagick.

Try:

```bash
vips magickload DSC_0037.NEF test.png
```

It might work.

**Comment by shilpi230** [comment]
It works thank you :D

**Comment by shilpi230** [comment]
I am facing another issue as we know that RAW files are basically handled by ufraw-batch and it supports one argument called EXPOSURE to remain the brightness of image. How can i get the same argument to work in VIPS.
