### ISSUE TITLE
Vips Python Multithreading

### ISSUE THREAD

**Issue by CodeEXc** [jcupitt/libvips#376]
How can I use an image in multiple threads (Python)? 
I want to crop and save a very large image in different threads.

But I just get errors like this:
vips_thread_shutdown() not called for thread 0x7f51bc02ae40`

**Comment by jcupitt** [comment]
Hi, there are some notes about this in the docs:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-vips.html#vips-thread-shutdown

The problem is that vips uses quite a lot of thread-private data, and there is no portable way to free this data automatically for threads which are not created by vips. You'll need to look into the Python threading library you are using and add a call to `vips_thread_shutdown()` just before each thread that uses vips exits.

You can call this function from Python as:

```
Vips.thread_shutdown()
```

**Comment by jcupitt** [comment]
I think I maybe just saw your post on stackoverflow:

http://stackoverflow.com/questions/35106760/how-to-handle-large-images

As I posted there, if you are making google maps pyramids, you should look at `dzsave`:

http://libvips.blogspot.co.uk/2013/03/making-deepzoom-zoomify-and-google-maps.html

It should do exactly what you need and be very fast.

**Comment by CodeEXc** [comment]
@jcupitt 
Thanks for your quick reply . I will check this.

**Comment by jcupitt** [comment]
Just saw your edit. 

`dzsave` should be there, if it's missing you probably had configure problems. It needs `libgsf-1-dev`, try running configure again and check the summary at the end.

**Comment by jcupitt** [comment]
Is this resolved? Please reopen if not.
