### ISSUE TITLE
Problem adding text annotation image to tif RGB16 image

### ISSUE THREAD

**Issue by apacheark** [jcupitt/libvips#381]
I am trying to add some text annotation to an RGB16 image with no luck.  I do not see the annotation for TIFF images (RGB16).  This works fine for a JPG sRGB image.  The TIFF (or JPG images are all the same size in pixels.

System: vips/libvips 8.2.2 on ubuntu 14.04.

Here is the python code I am using. If I use JPG images for rim,gim,bim then I can see the annotation just fine.  If I use TIFF images for rim,gim,bim, then no annotation text.  The TIFFs are RGB16.  
Any help is greatly appreciated!

    # Check image format
    if os.path.exists(in_img_path + "Tile001000.tif"):
        im_type =  ".tif"
    elif os.path.exists(in_img_path + "Tile001000.jpg"):
        im_type =  ".jpg"
    
    rim = Vips.Image.new_from_file(in_img_path+r_name,access = Vips.Access.SEQUENTIAL)
    gim = Vips.Image.new_from_file(in_img_path+g_name,access = Vips.Access.SEQUENTIAL)
    bim = Vips.Image.new_from_file(in_img_path+b_name,access = Vips.Access.SEQUENTIAL)

    compimg=rim.bandjoin([gim,bim])
    
    frmtext = Vips.Image.text("Frame: 00080", dpi = 150)
    compimg=compimg.insert(frmtext.rot90(), 1335, compimg.height-1000, expand = True)

    if im_type=='.jpg':
        compimg=compimg.copy(interpretation='srgb')
    elif im_type=='.tif':
       compimg=compimg.copy(interpretation='rgb16')

**Comment by jcupitt** [comment]
Hi @apacheark, it's because the colourspace of the text and the image don't match.

16-bit images use 0 - 65535 for black to white, 8-bit images use 0 - 255. If you try this program on a 16-bit image:

```python
#!/usr/bin/python

import sys
from gi.repository import Vips

im = Vips.Image.new_from_file(sys.argv[1])

txt = Vips.Image.text("Frame: 00080", dpi = 150)
im = im.insert(txt.rot90(), 10, 10)

im.write_to_file(sys.argv[2])
```

And take a look at the output, you'll see what seems to be a black box at the top-left. If you turn up the brightness a lot, you should start to see text inside it. It has rendered the text, but at 0 - 255, so it seems almost black when you paste into the 0 - 65535 image.

A simple fix is to change the colourspace of the text image before you insert it. Add a line like this:

```python
txt = Vips.Image.text("Frame: 00080", dpi = 150)
txt = txt.colourspace(im.interpretation)
im = im.insert(txt.rot90(), 10, 10)
```

Now the text is converted to the image colourspace before being pasted in.

**Comment by apacheark** [comment]
That did the trick.  Thanks for the help!

**Comment by jcupitt** [comment]
Good stuff. I'll close.
