### ISSUE TITLE
draw_line function and colors

### ISSUE THREAD

**Issue by apacheark** [jcupitt/libvips#396]
I am trying to draw a crosshairs on a color composite image.
The original image, borderimg, is an 'rgb16' image and I am using the code below to draw 4 lines on it.
No matter what I change the first argument (the draw value I have tries are 0, 128 and 255), the color of the 4 lines is always black.  I would like to have a white line draw on top of the original image.

Any ideas here as to what I am doing wrong?  I am using (lib)Vips 8.2 (python API) on Ubuntu 14.04.
`  

    borderimg = borderimg.draw_line(255.0,0,128,20,128)

    borderimg = borderimg.draw_line(255.0,128,0,128,20)

    borderimg = borderimg.draw_line(255.0,256,128,236,128)

    borderimg = borderimg.draw_line(255.0,128,256,128,236)

`

**Comment by jcupitt** [comment]
`rgb16` images have pixels in the range 0 - 65535 (2 ** 16 - 1), so you need to use 65535 instead of 255. 

Because of the way vips works, `draw_line` won't work well on large images, I expect you know. You'll find it's much faster to cut out the bit you want to draw on with `crop`, do a series of draw operations on it, then paste the modified image back with `insert`.

**Comment by jcupitt** [comment]
Did this fix it? Please reopen if it didn't.
