### ISSUE TITLE
Missing git tags for 8.2.x

### ISSUE THREAD

**Issue by jonnor** [jcupitt/libvips#403]
On http://www.vips.ecs.soton.ac.uk/supported/current/  there are releases for 8.2.0, 8.2.1 and 8.2.2. But here in the git repository there are no tags for these.
This makes it hard to find out what changes went into each version. It also makes it seem on Github like there has not been any releases recently...

**Comment by jonnor** [comment]
In https://github.com/jcupitt/libvips/blob/master/ChangeLog there is also mentioned `27/1/16 started 8.2.3`.
I don't know if "started" means released (seems so, since all older versions just have this changelog entry also?). This version has no tag nor tarball

**Comment by jcupitt** [comment]
Hi Jon, libvips uses branches for releases, so `git checkout 8.2` gets you the latest supported version. It's accumulated a few small things since the last release (8.2.2), so it's versioned as 8.2.3.

master is the in-progress 8.3.0 -- it's also got all of the 8.2.3 changes in. 

Does that make sense? There are a few tags too, but they are used to mark the point where master branched to make the start of a release. There should probably be more of these.

**Comment by jcupitt** [comment]
I've added some more tags and I'll try to remember to tag in the future. Thanks for flagging this up.
