### ISSUE TITLE
Cannot Resize an Image to 1px "shrinkv: image has shrunk to nothing"

### ISSUE THREAD

**Issue by aarti** [jcupitt/libvips#469]
I am trying to resize an image to 1px and I get this error

**Comment by jcupitt** [comment]
Hi @aarti, can you give some more details? What kind of image are you resizing, what command did you use, what language and platform?

If you are using `vips resize` on the command-line, you can get width/height going to zero due to rounding errors. If you want to shrink any image to exactly one pixel, `vips shrink` is probably a better choice. It implements a box filter: it replaces each pixel with the average of a rectangular area of pixels. 

For example:

```
john@kiwi:~/pics$ vipsheader k2.jpg 
k2.jpg: 1450x2048 uchar, 3 bands, srgb, jpegload
john@kiwi:~/pics$ vips shrink k2.jpg x.png 1450 2048
john@kiwi:~/pics$ vipsheader x.png
x.png: 1x1 uchar, 3 bands, srgb, pngload
```

**Comment by jcupitt** [comment]
I'll close, I think this is done.
