### ISSUE TITLE
vipsthumbnail resizes images improperly for larger than 128 thumbnails

### ISSUE THREAD

**Issue by figandbones** [jcupitt/libvips#472]
I'm having trouble with some very large (3GB+) png images. I can tile the images fine using vips dzsave, and also vipsthumbnail works with the default 128 resize. But I'd like a thumbnail around 500.

Using libvips 7.38, I get images such as this:

![tn_3197xn19c-no3-476 thumb 400 bob](https://cloud.githubusercontent.com/assets/5026261/16179179/f38332f8-3612-11e6-8455-a44a6978f8a3.jpg)

Using libvips 8.2, the images look like:

![tn_3197xn19c-no3-476](https://cloud.githubusercontent.com/assets/5026261/16179211/e0a95b84-3613-11e6-9bb1-1889b9d2dfbb.jpg)

Also with 8.2 there are thousands of warnings like:

`vips warning: linecache: error reading tile 0x38760: vipspng: out of order read at line 40288`

But I think the images are ok, since the tiling works and so does the default resize. I've tried several different sizes, including 512 (thinking maybe a power of two would help).

Any help would be very much appreciated.

**Comment by jcupitt** [comment]
Oh dear, sorry it's failing @figandbones. 

A simple fix for 8.2 is to disable vips's threadpool. Add `--vips-concurrency=1` to the `vipsthumbnail` command. It shouldn't be any slower.

A better fix would probably be to update to 8.3. It has an all-new image resizing system that's faster, better quality, and it should be impossible for these black strips to appear.  I tried a couple of 3gb PNG files on my laptop and it worked. 

The problem was the way that the block shrink operation asked for input pixels. It read tiles left-to-right, but each tile top-to-bottom. If you had many threads running and one thread was delayed for some reason, they could get out of order by the time they demanded pixels from the png reader. There's a thing to reorder threads, but there was a limit to how much disorder it could correct and sometimes it failed. 

The new shrinker uses a much simpler (and faster) top-to-bottom scheme and it should be impossible for ordering to break.

**Comment by figandbones** [comment]
Thanks @jcupitt. Actually there isn't any improvement with 8.3. Which is curious, since I got the same black stripe and warnings as before. I was almost sure the upgrade didn't work; but I checked and I am indeed using 8.3.

But disabling the threadpool did the trick.

I can send you a file if you're interested in testing.

**Comment by jcupitt** [comment]
The file contents (probably) don't matter. Could you send the exact specs? I should be able to make one here. I tested with this one:

```
$ vipsheader x.png
x.png: 35699x33600 uchar, 3 bands, srgb, pngload
```

I guess yours might be 4 bands?

**Comment by figandbones** [comment]
Yes.

vipsheader tm70mw229-no3-118.png
tm70mw229-no3-118.png: 136136x88713 uchar, 4 bands, srgb, pngload

**Comment by jcupitt** [comment]
Oh that's a bit bigger than I was trying. I'll have another go.

**Comment by figandbones** [comment]
Here's a smaller one with the same problem:

vipsheader 3197xn19c-no3-476.png
3197xn19c-no3-476.png: 76160x51468 uchar, 4 bands, srgb, pngload

**Comment by jcupitt** [comment]
It took a while, but it worked for me. 

```
$ time vipsthumbnail x.png -s 500
real	14m7.635s
user	14m2.536s
sys	0m8.776s
```

What kind of machine and OS are you running?

**Comment by figandbones** [comment]
I have a macbook pro (2.2GHz Intel Core i7) with OSX 10.11. And as you said, it's no slower with the threadpool disabled.

```
$ ll 3197xn19c-no3-476.png
-rw-r--r--  1 diana  staff  3840179039 Jun 19 11:34 3197xn19c-no3-476.png
$ time vipsthumbnail 3197xn19c-no3-476.png -s 500 > vipsthumbnail.out 2>&1

real	2m49.857s
user	2m47.299s
sys	0m5.466s
$ time vipsthumbnail 3197xn19c-no3-476.png --vips-concurrency=1 -s 500

real	2m52.497s
user	2m47.399s
sys	0m3.273s
```

**Comment by felixbuenemann** [comment]
Might be related to issue #426.

**Comment by jcupitt** [comment]
I tried on my imac with a couple of huge png images and couldn't reproduce this, unfortunately.

**Comment by jcupitt** [comment]
Sorry, can't reproduce :( Please reopen if a simpler test case comes up.
