### ISSUE TITLE
how to build on lambda

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#492]
_From the vips mailing list_

A fellow named Felix has a script for compiling VIPS for lambda at https://gist.github.com/felixbuenemann/742f1fdac998b17bfcda

This works great, if you don't need image pyramid supports, which I do. But the libgsf requirement is killing me. I can't find it in any of the YUM repositories. Attempting to download the rpm and install it takes me down a list of dependencies that ultimately I can't find an RPM for sub-libraries.

I've tried building it from source, but even building it from source and using the same --prefix the libvips configure doesn't see the library. Although I wonder if that is actually building the devel libraries and installing them, or if it is just building the libgsf library?

Regardless, I've about given up on image pyramid support in Lambda due to the dependency.

If anyone knows of a way to to build it, I'm testing on Amazon Linux AMI release 2015.09, with image pyramid support, I'd be eternally grateful if you shared your secret with me. Or, just zip up the executable and libraries that run on Lambda and send them to me? :-)

**Comment by jcupitt** [comment]
This has some useful notes: http://sharp.readthedocs.io/en/stable/install/#aws-lambda

**Comment by lovell** [comment]
`sharp` supports image pyramids using the [tile](http://sharp.dimens.io/en/stable/api/#tileoptions) operation, and includes `libgsf` in its pre-compiled binaries so there's no need to globally install either it or libvips.

**Comment by jcupitt** [comment]
I think @bubba-h57 is not using node, he just needs vips on lambda.

**Comment by bubba-h57** [comment]
Yes, I've historically used python and vips, or vips on the command line. I'd like to not have to rewrite all my code. However, it would be nice if the pre-compilied binaries in sharp included the executable. All I really need are the pre-compiled binaries with it. However, when I looked, it appeared there is not actual binary included, just an .so

**Comment by bubba-h57** [comment]
Given that `sharp` is already building pre-compiled binaries, how about a write up on how you do it?

**Comment by bubba-h57** [comment]
It looks like sharp isn't building for the latest image?

https://gist.github.com/brianreavis/b0e1141453e616f1b990#file-libvips-sh-L283

**Comment by lovell** [comment]
The "pre-compiled binaries" that sharp distributes are the shared libraries. These are created by various Docker-managed [containers and scripts](https://github.com/lovell/sharp/tree/master/packaging) and published to Bintray to be retrieved by sharp at `npm install` time. You might be able to adapt these packaging scripts for your purposes.

The old preinstall.sh script to globally-install libvips is deprecated and I plan to remove it at some point. It was too complex and didn't solve the right problem (namely a dependency-less, non-global runtime).

There's been some talk at https://github.com/lovell/sharp/issues/463 about creating a space in libvips' Wiki with all the "how to install libvips" information.

**Comment by bubba-h57** [comment]
So you are actually building it in `debian:wheezy` and the resulting libraries *just work* in the *Amazon Linux AMI* used in *Lambda* ?

**Comment by lovell** [comment]
@bubba-h57 Yes, the shared libraries built on wheezy assume only the presence of glibc v2.13+ at runtime (IIRC the latest Amazon Linux is glibc v2.17). sharp itself is compiled as a shared library and uses the linker's [rpath](https://github.com/lovell/sharp/blob/master/binding.gyp#L165-L166) flag to ensure it can see the pre-compiled shared libraries.

**Comment by felixbuenemann** [comment]
I'm currently building libvips and lots required libraries including the gobject instrospection dependencies for Python using a matching Amazon Linux AMI.

As it is I'm doing this manually (which is a PITA), but it should be possible to bundle all the steps up into a script that could be run in an [amazon linux docker container](https://hub.docker.com/r/ambakshi/amazon-linux/).

The build could also happen on another distribution, but you would have to build even more libraries. 

If you build your own libraries, it's easiest to compile them with `--prefix=/var/task` because that's were they will live in the actual lambda environment and it allows to to properly load the right libraries, even if the overshadow older system versions. For example I'm using the [cloudflare/zlib](https://github.com/cloudflare/zlib) fork to speed up PNG.

In addition to libvips I'm currenlty building vendored versions of libcairo, libcroco, libexif, libfftw3, libgdk_pixbuf, libgirepository, libgsf-1, libharfbuzz-icu, mozjpeg, liborc, libpango, libpangocairo, libpangoft2, libpng16, libpoppler-glib, librsvg-2, libwebp and libz.

That covers most of the fileformats supported by vips. You can get by with a LOT less libraries if you can get by with basic jpeg, png, tiff support and don't care if you have the latest version.

I am doing on-the-fly processing of very high res images, so I need every last bit of speed I can get.

@bubba-h57 I'm sure I can give you some hints if you run into trouble.

If you want something quick to get started, I could also give you a copy of my current lambda-python-vips skeleton zip and Makefile, which has all of the libs above and libvips master from mid May. The Makefile adds your handler code from the current dir, adds it to a new zip based on the skeleton and deploys it using the AWS cli.

@lovell Thanks for the `-rpath` hint, that would probably allow me to build with a different prefix than `/var/task`.

**Comment by bubba-h57** [comment]
Thanks

**Comment by felixbuenemann** [comment]
Btw. AWS released an official Docker image for Amazon Linux a short while ago that can probably be used for building locally without an EC2 instance:

* [Blog Post announcing the Amazon Linux Container Image](https://aws.amazon.com/blogs/aws/new-amazon-linux-container-image-for-cloud-and-on-premises-workloads/)
* [Instruction on how to get the Image from AWS ECR](http://docs.aws.amazon.com/AmazonECR/latest/userguide/amazon_linux_container_image.html)

**Comment by bubba-h57** [comment]
Thanks guys, I believe I now have what I was looking for! https://github.com/stechstudio/libvips-lambda

**Comment by metaskills** [comment]
Sharing work on how I did this with `lambci/lambda` Docker images for the Ruby runtime. 

https://github.com/customink/ruby-vips-lambda

People might find it interesting that we avoided the `glib` and `gobject` installs since they are already present on AWS Lambda. All in all the process was really simple depending on your needs. For Ruby, we use the ruby-vips gem which uses FFI, so all we had to do was the shared libraries in place. Hope that helps someone else approaching this issue.

**Comment by bubba-h57** [comment]
Very nice.

**Comment by jcupitt** [comment]
There's some more discussion here: https://github.com/libvips/ruby-vips/issues/194

**Comment by lundin** [comment]
Hi!
Is there any way one can explain how to build (what do i need to zip to a lambda deploy package to make vips work in a amazon linux/lambda enviroment ?)

I tried the first shell script in this thread it seems no longer working. Tried all sorts of builds on Amazon EC2 to no avail.

However I build vips with package manager using docker from here:
https://github.com/libvips/libvips/issues/1184 (remi last post)

But what i dont understand is what do i need to copy/zip in order to do a exec of the vips shell command using golang. Can i even do that (take the vips binary etc) from this docker image and put into the lambda ?

Thanks :)

**Comment by felixbuenemann** [comment]
I also skipped the glib and gobject binding in my python based project, but I had to do quite a bit of patching or using older versions of other dependencies like poppler and rsvg to make it work with the relatively ancient versions in lambda, but it really helps to bring the binary size down.

AWS has recently updated their lambda execution environment based on Amazon Linux 2018.03, so this might become much easier.

See [Upcoming updates to the AWS Lambda and AWS Lambda@Edge execution environment](https://aws.amazon.com/de/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/) on the AWS Compute Blog.

**Comment by felixbuenemann** [comment]
Just checked and Amazon Linux 2018.03 still ships with `glib2-2.36.3-5.18.amzn1.x86_64`, the same version it used in the initial AWS Lambda environment based on Amazon Linux 2015.09.

Older functions that have not been updated to the new environment are currently based on Amazon Linux 2017.03.

**Comment by felixbuenemann** [comment]
Fyi I've been doing some more work on porting my EC2 based build into a Dockerfile that could also be used to build a Lambda Layer with a few modifications.

So far I've got the following libs built against the old-ish system glib:

* Cloudflare zlib: gcc.amd64
* libpng: libpng16
* mozjpeg: master
* gobject-introspection: GOBJECT_INTROSPECTION_1_43_3 (could be dropped)
* libtiff: master + patch to fix warnings with Photoshop TIFFs
* cairo: 1.16 + patch to fix compile with old lambda freetype2
* libcroco: master
* ragel: 6.10 (required for build)
* harfbuzz: 0.9.37
* pango: 1.40.5 + patch to work with older fontconfig
* gdk-pixbuf: 2.28.2
* librsvg: 2.40.20
* poppler: poppler-0.68.0 + patches to compile with older cmake and glib

**Comment by willfarrell** [comment]
@felixbuenemann were you successful in creating a Lambda Layer w/ vips installed? I'm looking to create one with `libheif` support enabled.
