### ISSUE TITLE
How to use the VIPS library from Microsoft Visual C++ project ?

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#508]
Hi,

I am looking for a way to build a short program (compile and link) that uses the VIPS C++ API library.
The program is Visual C++ Win32 Console Application running under Visual Studio 2015 project, VC14, in Windows 7 64bit station.

I downloaded the 'vips-dev-w64-all.8.3.3a.zip' - It has a complete set of header/lib/dll folders for VIPS. All these folders were copied to the project directory.

The code looks like the following:
# include "stdafx.h"
# include <iostream>
# include <vips/vips>

int main( int argc, char **argv )
{
        try {
                vips::VImage fred( argv[1] );

```
            fred.invert().write( argv[2] );
    }
    catch( vips::VError e ) {
            e.perror( argv[0] );
    }

    return( 0 );
```

}

I've added all necessary include directories for header files: 
.\Visual Studio 2015\Projects\ConsoleApplication1\include;
.\Visual Studio 2015\Projects\ConsoleApplication1\include/glib-2.0;
.\Visual Studio 2015\Projects\ConsoleApplication1/lib/glib-2.0/include

and set all *.lib files found in the zip as the library files to be used:
.\Visual Studio 2015\Projects\ConsoleApplication1/lib

but the build failed with:
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: void __cdecl vips::VImage::refblock::removeref(void)" (?removeref@refblock@VImage@vips@@QEAAXXZ) referenced in function "public: virtual __cdecl vips::VImage::~VImage(void)" (??1VImage@vips@@UEAA@XZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __cdecl vips::VImage::VImage(char const *,char const *)" (??0VImage@vips@@QEAA@PEBD0@Z) referenced in function main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: class vips::VImage __cdecl vips::VImage::write(char const *)" (?write@VImage@vips@@QEAA?AV12@PEBD@Z) referenced in function main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: class vips::VImage __cdecl vips::VImage::invert(void)" (?invert@VImage@vips@@QEAA?AV12@XZ) referenced in function main
1>c:\users\itzika\documents\visual studio 2015\Projects\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe : fatal error LNK1120: 4 unresolved externals
StopOnFirstBuildError: Build cancelled because project "ConsoleApplication1" failed to build.
Build has been canceled.

Did I miss something? Your help will be appreciated.

Thanks.

**Comment by jcupitt** [comment]
Hi  @alonit,

Unfortunately, you can't mix compilers in C++ projects. You need to use the same compiler for every component, and it's probably a good idea to match the version too. This is because of things like name mangling and static initialization, where compilers vary in the rules they use. I used gcc 5.4 to make the Windows binary, so you need to use gcc 5.4 for your project too.

I think you have two alternatives. You can use the C API, which will work across compilers, or you can rebuild just the C++ layer with MSVC. The people using libvips from node do this, I think they have a project file you can download to do the build, or you can do it yourself, it's pretty simple. 

The source for the C++ layer is here:

https://github.com/jcupitt/libvips/tree/master/cplusplus

It's just those four files, plus the matching includes.

**Comment by alonit** [comment]
Hi jcupitt,

Thanks for your reply.

I tried to compile the C++ API from the link you attached above. I've added the 4 .h and .cpp files to an empty VC++ project, set the include directories and libraries to point to their location in 8.3 folder, but the build failed.
Attached is the build output log file, and the Visual Studio project layout print screen.
![vip_api_vc_project](https://cloud.githubusercontent.com/assets/21310386/18082180/5abfe2ba-6ea6-11e6-930e-addf79b4b462.png)
[BuildLog.txt](https://github.com/jcupitt/libvips/files/444365/BuildLog.txt)

In addition I'v looked at https://github.com/lovell/sharp, but can't find their MSVC project file.

Your help would be greatly appreciated.

Many thanks.

**Comment by jcupitt** [comment]
Don't try to compile `vips-operators.cpp` directly, it gets included by `VImage.cpp`. It's automatically generated. 

You'll find you need a few `-D` to make the DLL exports work correctly with MSVC. Have a look at the source.

@lovell, is there an easy link to the project file you use for node?

**Comment by lovell** [comment]
The MSVC project files for sharp are generated using [gyp](https://gyp.gsrc.io/) via the [node-gyp](https://github.com/nodejs/node-gyp) wrapper.

My (unsupported, experimental) attempts at building only the `libvips-cpp.dll` file in a similar manner can be found at https://github.com/lovell/libvips-cpp-dll

**Comment by mms-** [comment]
c# bindings would be nice!

**Comment by jcupitt** [comment]
Sorry, C# is long way outside my area, but of course I'd be very happy to help anyone who wanted to have a go.

**Comment by jcupitt** [comment]
It seems people are using libvips successfully from C# via p/invoke, so a full binding shouldn't be hard.

**Comment by angelmixu** [comment]
Hi @jcupitt !
I'm migrating a project using vips 7.x on VS2005 to vips 8.4 on VS2015 and I found a similar error like this issue.
I've downloaded the latest stable binary version, vips-dev-w64-all-8.4.4.zip, and updated libraries, headers, and made some 'compatibility' code for what our project was using before.

I'm stuck at this linker error, and also with missing pangoft2 headers/libraries.

At first, in the zip file there's no pangoft2* files inside 'vips-dev-8.4\include\pango-1.0\pango\' directory, while in the official release of pango is (I think in vips 7.x there were pangoft2* files). It's not much of an issue, because I can rebuild pango with free type support, but I wonder if there is another way that I'm not aware of in vips for using pango with freetype.

Apart from that, the main issue is this link error:

```
4>myvipsc++.obj : error LNK2001: unresolved external symbol "void __cdecl vips::verror(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?verror@vips@@YAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl vips::VDisplay::~VDisplay(void)" (??1VDisplay@vips@@UEAA@XZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::_private_detail::VPDMask::VPDMask(int,int,double,double,class std::vector<double,class std::allocator<double> >)" (??0VPDMask@_private_detail@vips@@QEAA@HHNNV?$vector@NV?$allocator@N@std@@@std@@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: class vips::VMask & __cdecl vips::VMask::operator=(class vips::VMask const &)" (??4VMask@vips@@QEAAAEAV01@AEBV01@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl vips::VMask::~VMask(void)" (??1VMask@vips@@UEAA@XZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: void __cdecl vips::VDMask::embed(struct im__DOUBLEMASK *)" (?embed@VDMask@vips@@QEAAXPEAUim__DOUBLEMASK@@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: double & __cdecl vips::VDMask::operator[](int)" (??AVDMask@vips@@QEAAAEANH@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: class vips::VDMask __cdecl vips::VDMask::mul(class vips::VDMask)" (?mul@VDMask@vips@@QEAA?AV12@V12@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: void __cdecl vips::VImage::refblock::addref(struct vips::VImage::refblock *)" (?addref@refblock@VImage@vips@@QEAAXPEAU123@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: void __cdecl vips::VImage::refblock::removeref(void)" (?removeref@refblock@VImage@vips@@QEAAXXZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(void *,int,int,int,enum vips::VImage::TBandFmt)" (??0VImage@vips@@QEAA@PEAXHHHW4TBandFmt@01@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(struct _VipsImage *)" (??0VImage@vips@@QEAA@PEAU_VipsImage@@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(void)" (??0VImage@vips@@QEAA@XZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(class vips::VImage const &)" (??0VImage@vips@@QEAA@AEBV01@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: class vips::VImage & __cdecl vips::VImage::operator=(class vips::VImage const &)" (??4VImage@vips@@QEAAAEAV01@AEBV01@@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::Vargv::Vargv(char const *)" (??0Vargv@vips@@QEAA@PEBD@Z)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::Vargv::~Vargv(void)" (??1Vargv@vips@@QEAA@XZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: void __cdecl vips::Vargv::call(void)" (?call@Vargv@vips@@QEAAXXZ)
```

I've tried the solution mentioned before for building a c++ DLL linkage, but it still leaves most of the link errors except these two:

```
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(void)" (??0VImage@vips@@QEAA@XZ)
4>myvipsc++.obj : error LNK2001: unresolved external symbol "public: __cdecl vips::VImage::VImage(class vips::VImage const &)" (??0VImage@vips@@QEAA@AEBV01@@Z)
```

The use of those classes inside our code is a wrapper around VImage and VDMask:
```

class __declspec(dllexport) myVImage : public VImage
	{
	public:

	// Plain constructors

	myVImage();
	myVImage( const char *name, const char *mode = "r" ) throw( VError );
	myVImage( void *data, int width, int height, 
		int bands, TBandFmt format ) throw( VError );
	myVImage( VipsImage *image );

[...]

myVImage::myVImage( void *data, int width, int height, int bands, TBandFmt format ) throw( VError )
	: VImage ( data, width, height, bands, format )
{
}

myVImage::myVImage( VipsImage /*im__IMAGE*/ *image )
	: VImage(image)
{
}
```


I can see, for example, that the constructor with a void, 3 ints, and a TBandFmt is in VImage.h header, but not in VImage8.h.


We are stuck in this step and have no idea what to do next.
Would you know how to fix this or any thing to try?
Thanks in advance!

**Comment by jcupitt** [comment]
Hello, there are now two C++ APIs, I think you may be trying to use a mixture of them.

There's a vips7 C++ interface generated by SWIG that you can still use (that's the `VDIMask` stuff), and there's a new vips8 interface that's much simpler and more flexible (that's the `vips8` headers).

How much code do you have to move over? If it's not much, I would consider a rewrite for the new vips8 API, because it's a lot nicer. Additionally, thanks to work on the libvips binding for node on Windows, it should build easily.

There are some notes on it here:

http://jcupitt.github.io/libvips/API/current/using-from-cpp.html

So I would recommend:

1. Make a local copy of the `vips-8.5.x/cplusplus` directory and build that with your version of MSVC. You shouldn't need to make any changes, lots of people build this tree with no issues (I think).

2. Make a tiny "hello world" program using the new API and get that running.

3. Rework your project!

**Comment by angelmixu** [comment]
Thanks!

As I can see there's a bunch of code I should move/migrate over, but I'll talk to the project owner and comment about the new interface for if reworking it is viable.

Regarding step 1, I did it and In VImage8.h I had to remove VIPS_CPLUSPLUS_API from functions that return a reference, like operator+= one's, in order to compile correctly.

```
1>...\depends\common\vips\vimage8.h(784): error C2059: syntax error: '__declspec(dllexport)' (compiling source file ..\Depends\Common\vips_cpp_binding\VError.cpp)
1>...\depends\common\vips\vimage8.h(784): error C2059: syntax error: '__declspec(dllexport)' (compiling source file ..\Depends\Common\vips_cpp_binding\VImage.cpp)
1>...\depends\common\vips\vimage8.h(784): error C2238: unexpected token(s) preceding ';' (compiling source file ..\Depends\Common\vips_cpp_binding\VError.cpp)
1>...\depends\common\vips\vimage8.h(784): error C2238: unexpected token(s) preceding ';' (compiling source file ..\Depends\Common\vips_cpp_binding\VImage.cpp)
1>...\depends\common\vips\vimage8.h(785): error C2059: syntax error: '__declspec(dllexport)' (compiling source file ..\Depends\Common\vips_cpp_binding\VError.cpp)
1>...\depends\common\vips\vimage8.h(785): error C2059: syntax error: '__declspec(dllexport)' (compiling source file ..\Depends\Common\vips_cpp_binding\VImage.cpp)
1>...\depends\common\vips\vimage8.h(784): error C2059: syntax error: '__declspec(dllexport)' (compiling source file ..\Depends\Common\vips_cpp_binding\VInterpolate.cpp)
1>...\depends\common\vips\vimage8.h(785): error C2238: unexpected token(s) preceding ';' (compiling source file ..\Depends\Common\vips_cpp_binding\VError.cpp)
1>...\depends\common\vips\vimage8.h(785): error C2238: unexpected token(s) preceding ';' (compiling source file ..\Depends\Common\vips_cpp_binding\VImage.cpp)
1>...\depends\common\vips\vimage8.h(784): error C2238: unexpected token(s) preceding ';' (compiling source file ..\Depends\Common\vips_cpp_binding\VInterpolate.cpp)
[...]
```

Looking for those errors I got these two links which are similar to this case, only happening on functions returning a reference:

http://howcanfix.com/86762/return-reference-to-object-in-dll
https://forum.juce.com/t/windows-dll---declspec-dllimport-placement/5793

But changing it in that way didn't fix the compiler error. It's quite strange :/

**Comment by jcupitt** [comment]
I'm very surprised you needed to remove the `VIPS_CPLUSPLUS_API`, they should be necessary to make a DLL. Have MS really changed the way these declarations are used in VS2015? This could be a real pain.

@lovell, I don't suppose you've come across this?

**Comment by jcupitt** [comment]
Ooop sorry for pinging you @lovell 

@angelmixu, are you defining `VIPS_CPLUSPLUS_EXPORTS`? You must define this before you build a DLL. The logic is in the `vips8` header:

```c++
/* Define VIPS_CPLUSPLUS_EXPORTS to build a DLL using MSVC.
 */
#ifdef _MSC_VER
#  ifdef VIPS_CPLUSPLUS_EXPORTS
#    define VIPS_CPLUSPLUS_API __declspec(dllexport)
#  else
#    define VIPS_CPLUSPLUS_API __declspec(dllimport)
#  endif
#else
#  define VIPS_CPLUSPLUS_API
#endif
```

**Comment by angelmixu** [comment]
@jcupitt yes, I'm defining it on the project DLL.
If I don't define it the errors show '__declspec(dllimport)' instead of dllexport one's.

**Comment by angelmixu** [comment]
I've uploaded a sample project here:
https://drive.google.com/file/d/0B7nLd3NWlDVfRGpxZVFsang5cHM/view?usp=sharing

It's a new win32 project, with exported as DLL using the VS2015 wizard.

**Comment by lovell** [comment]
#540 is probably what is needed here, which requires libvips v8.5+.

**Comment by angelmixu** [comment]
@lovell thanks! Now it compiles and links for the v8 interface :D
After talking with the project owner, he thinks migrating our code for v8 interface at this moment is a very big change, and as @jcupitt said there's a v7 interface, we should use v7 in the meantime.

But, I'm trying to use the v7 interface, from version 8.5.4 (the libvipsCC directory), and building a DLL like the project before, and there's a bunch of different errors. If I define SWIG there are another bunch of errors, I have been trying to fix them in both cases but I think I don't know enough about the insides of the library to be able to fix them.

Here's the DLL project I built for v7 interface for if you can take a look:
https://drive.google.com/file/d/0B7nLd3NWlDVfcjBScjZyRGJTbVU/view?usp=sharing

Apart from that, we use vips on win32 too, and other platforms. What do you think the best approach would be for using the v7 interface?
Should we build the library from sources creating our own VS project for example, and then creating dll's or static libraries for other platforms?
Should we build the sources with SWIG macro defined?

Thanks for you help!

**Comment by jcupitt** [comment]
Sorry, I've not built the v7 C++ interface with MSVC, I can't really help there. 

Don't define `SWIG`. This is only set when the headers are passed through SWIG to generate the v7 Python binding. 

The problem only occurs if you use C++ on Windows. This isn't an issue on other platforms -- you can just use the standard libvips package.

The problem is that C++ does not define an ABI (a binary interface), so you can't mix compiler versions in a single project. Things like name mangling, and initialization differ, sometimes even between minor versions of the same compiler, and you'll find a range of frustrating link and run time errors. 

There isn't a free MS compiler, so we have to build the Windows binaries we distribute with gcc. You must therefore use gcc to build your project, or rebuild the C++ parts of vips with MSVC and then use C linkage to link to the gcc-built vips core. 

How many lines of code do you have using the v7 interface? If it's less than 1,000, I'd think it would only be a day's work to revise for v8, they are not that different. You should find it turns into less code as well: the v8 interface does quite a bit more for you.

**Comment by angelmixu** [comment]
Thanks John!
The main module is like 3550 lines, and there are around 60 small files using vips. So, it is a big codebase around vips :/

What I've been trying to do is compiling the library with v7 interface on VS2015 and I've been succesfull, I had to make some small changes but it passed most of our unit tests :D

I'm still testing for errors on our enveloping code, but looks fine at the moment.

About a free MS compiler, I'm using VS2015 community, which you can download for free from MS's Visual Studio webpage.

**Comment by jcupitt** [comment]
That is quite a bit of code. I'm pleased it's working!

**Comment by krushnavadan** [comment]
hi,
angelmixu and jcupitt , i am starting this project and starting to rewrite in c#,

**Comment by jcupitt** [comment]
I guess calling functions in the C DLL with p/invoke? I did a binding for Lua recently using FFI, which is similar to p/invoke:

https://github.com/jcupitt/lua-vips

It's a complete, high-level binding for the whole of libvips in 1600 lines of code, portable across Linux, macOS and Windows. The core is this bit:

https://github.com/jcupitt/lua-vips/blob/master/src/vips/voperation.lua#L143

It implements a function called `call` which can call any libvips operation by using introspection. 

There might be some ideas you could use.

**Comment by krushnavadan** [comment]
Thanks great , and is there way i can work with you,

**Comment by shipengtao** [comment]
@jcupitt @lovell @alonit @angelmixu Thanks for your discussion about using MSVC build cplusplus. I,m sorry,I can't compile by using your method. My environment : libvips-8.5.9/cplusplus , vips-dev-w64-all-8.5.9.zip  , Visual C++ *64 Console Application running under Visual Studio 2013 project, VC120, in Windows 10 64bit station.
I've added all necessary include directories and libs for this program, as follows:
`'include_dirs': [
          '<(module_root_dir)/libvips/cplusplus/include',
          '<(module_root_dir)/include',
          '<(module_root_dir)/include/glib-2.0',
          '<(module_root_dir)/lib/glib-2.0/include'
        ],
        'libraries': [
          '<(module_root_dir)/lib/libvips.lib',
          '<(module_root_dir)/lib/libglib-2.0.lib',
          '<(module_root_dir)/lib/libgobject-2.0.lib'
        ],`

![image](https://user-images.githubusercontent.com/22238105/33418163-89073906-d5df-11e7-9ea8-4b57c19cd779.png)

the main issue is this link error:
`1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) const vips::VOption::`vftable'" (__imp_??_7VOption@vips@@6B@)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class vips::VImage & __cdecl vips::VImage::operator=(class vips::VImage const &)" (__imp_??4VImage@vips@@QEAAAEAV01@AEBV01@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VImage::VImage(class vips::VImage const &)" (__imp_??0VImage@vips@@QEAA@AEBV01@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VImage::~VImage(void)" (__imp_??1VImage@vips@@QEAA@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VError::VError(class vips::VError const &)" (__imp_??0VError@vips@@QEAA@AEBV01@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class vips::VImage __cdecl vips::VImage::pow(double,class vips::VOption *)" (__imp_?pow@VImage@vips@@QEAA?AV12@NPEAVVOption@2@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class vips::VImage __cdecl vips::VImage::linear(double,class std::vector<double,class std::allocator<double> >,class vips::VOption *)" (__imp_?linear@VImage@vips@@QEAA?AV12@NV?$vector@NV?$allocator@N@std@@@std@@PEAVVOption@2@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class vips::VImage __cdecl vips::VImage::linear(class std::vector<double,class std::allocator<double> >,double,class vips::VOption *)" (__imp_?linear@VImage@vips@@QEAA?AV12@V?$vector@NV?$allocator@N@std@@@std@@NPEAVVOption@2@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: class vips::VImage __cdecl vips::VImage::linear(double,double,class vips::VOption *)" (__imp_?linear@VImage@vips@@QEAA?AV12@NNPEAVVOption@2@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class vips::VOption * __cdecl vips::VImage::option(void)" (__imp_?option@VImage@vips@@SAPEAVVOption@2@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: double __cdecl vips::VImage::yres(void)" (__imp_?yres@VImage@vips@@QEAANXZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: double __cdecl vips::VImage::xres(void)" (__imp_?xres@VImage@vips@@QEAANXZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: enum VipsInterpretation __cdecl vips::VImage::interpretation(void)" (__imp_?interpretation@VImage@vips@@QEAA?AW4VipsInterpretation@@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: enum VipsBandFormat __cdecl vips::VImage::format(void)" (__imp_?format@VImage@vips@@QEAA?AW4VipsBandFormat@@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl vips::VImage::bands(void)" (__imp_?bands@VImage@vips@@QEAAHXZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl vips::VImage::height(void)" (__imp_?height@VImage@vips@@QEAAHXZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: int __cdecl vips::VImage::width(void)" (__imp_?width@VImage@vips@@QEAAHXZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: struct _VipsImage * __cdecl vips::VImage::get_image(void)" (__imp_?get_image@VImage@vips@@QEAAPEAU_VipsImage@@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VImage::VImage(void)" (__imp_??0VImage@vips@@QEAA@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VImage::VImage(struct _VipsImage *,enum vips::VSteal)" (__imp_??0VImage@vips@@QEAA@PEAU_VipsImage@@W4VSteal@1@@Z)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: virtual __cdecl vips::VError::~VError(void)" (__imp_??1VError@vips@@UEAA@XZ)
1>VImage.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VError::VError(void)" (__imp_??0VError@vips@@QEAA@XZ)
1>VInterpolate.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VInterpolate::VInterpolate(class vips::VInterpolate const &)" (__imp_??0VInterpolate@vips@@QEAA@AEBV01@@Z)
1>VInterpolate.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VInterpolate::~VInterpolate(void)" (__imp_??1VInterpolate@vips@@QEAA@XZ)
1>VInterpolate.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: struct _VipsInterpolate * __cdecl vips::VInterpolate::get_interpolate(void)" (__imp_?get_interpolate@VInterpolate@vips@@QEAAPEAU_VipsInterpolate@@XZ)
1>VInterpolate.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl vips::VInterpolate::VInterpolate(struct _VipsInterpolate *,enum vips::VSteal)" (__imp_??0VInterpolate@vips@@QEAA@PEAU_VipsInterpolate@@W4VSteal@1@@Z)
1>E:\c\Projects\cppbuild\x64\Release\cppbuild.dll : fatal error LNK1120: 26 个无法解析的外部命令`

Would you know how to fix this or any thing to try?
Thanks in advance!

**Comment by jcupitt** [comment]
Hello @shipengtao,

You can't mix C++ compilers in a single project, since every compiler will have different name mangling rules and different ways of handling initialization. These rules can even change between minor compiler versions, so really you must build **every** C++ component in your project with exactly the same compiler. 

The C++ layer in the vips-dev bundle is built with gcc6, so if you use the precompiled libvips C++ binding, you must use gcc6 to build the rest of your project. 

I think your choices are:

### Use the C API
  
The precompiled libvips.dll uses the MS standard C ABI, so you can call it from any compiler. It's a bit more awkward to use than the C++ API, but it's not too bad really (in my opinion). This is the route I take on Windows.

### Build the C++ layer yourself

The libvips C++ layer is very simple, it's just these few files:

https://github.com/jcupitt/libvips/tree/master/cplusplus

You can just copy them somewhere and build them yourself in VS, it should be easy. Once you have a MSVC `libvips-cpp.dll`, you can just use that from your main project. This is the route that node on Windows takes.

**Comment by shipengtao** [comment]
@jcupitt Thanks for your reply! 
I am very sorry,i do not quite understand what you said about build every c++ component. c++ component is only have https://github.com/jcupitt/libvips/tree/master/cplusplus ?
My steps as follows:
1.copy VError.cpp VInterpolate.cpp VImage.cpp to my project, and add to VS Source Files
2.download vips-dev-w64-all-8.6.0-beta1.zip unzip to somewhere
3.add four directories to VS include directory:  libvips\cplusplus\include    vips-dev-8.6\include   vips-dev-8.6\include\glib-2.0     vips-dev-8.6\lib\glib-2.0\include
4.add a directory to VS lib directory: vips-dev-8.6\lib
5.add  three libs to VS Additional dependencies: libvips.lib   libglib-2.0.lib    libgobject-2.0.lib
6.build Configuration type is dll .
7.build  cplusplus
Follow the above steps, the compiler can not be completed, the error is as follows:
![image](https://user-images.githubusercontent.com/22238105/33442176-7a70193a-d62f-11e7-8148-3c0be6fce579.png)

The above steps are correct? If  wrong, please tell me how to solve it,thank you very much!

**Comment by lovell** [comment]
@shipengtao Is `VIPS_CPLUSPLUS_EXPORTS` defined when building the DLL, as mentioned in the comment https://github.com/jcupitt/libvips/issues/508#issuecomment-305161044 above?

**Comment by jcupitt** [comment]
Sorry, I don't use MSVC. But it should be simple: it's just those three source files. All you need to do is build them as a DLL.

**Comment by shipengtao** [comment]
@lovell @jcupitt  Thanks very much! According to your tips @lovell , I have solved this problem.
My solution is : project->setting->C/C++->Preprocessor definitions  add  VIPS_CPLUSPLUS_EXPORTS

**Comment by caishengzao** [comment]
@ml2tao  do you use msvc ?  i use qt with msvc ,but the same fault  still happened...
