### ISSUE TITLE
pdfload: no property named 'density'

### ISSUE THREAD

**Issue by asgerb** [jcupitt/libvips#523]
Probably not a bug, most likely just something wrong with my installation, but when running the following command:

`vipsthumbnail file.pdf[density=300,page=1] -o file.jpg[background=255] --size=1920x`

I get an error:

`pdfload: no property named 'density'`

It's a bit hard to find detailed documentation of the `density` parameter, so my usage is based on what I could read on various commit comments and issues here in the Github repo. Perhaps somebody can elaborate how to specify it when using `vipsthumbnail`?

```
$ vipsthumbnail --vips-version  
=> libvips 8.3.3-Tue Aug  9 10:41:33 BST 2016
````

**Comment by jcupitt** [comment]
Hi @asgerb, libvips has at least two different ways of loading PDF files, depending on how it's been configured.

Up until 8.2, it always used libMagick via the vips operation `magickload`. This worked by writing the PDF to a temoprary file, spawning a `gs` process and loading the bitmap that `gs` rendered. The `density` option is part of `magickload`. 

8.3 introduced a set of new native loaders to handle the formats that were most commonly handled by libMagick: PDF, GIF and SVG. We hoped to get better performance, and to avoid using libMagick if possible, because of the security implications of having such a huge package processing files from the internet. 

The new `pdfload` operation uses libpoppler to render a PDF directly into memory. It's much, much faster and uses far less memory.  It supports a slightly different range of options. 

So you have a choice: configure your libvips to use libMagick and continue to use the old options (you pass `--without-poppler` to configure), or enable libpoppler and slightly change your PDF options. 

You can see the options that `pdfload` supports by running the operation with no arguments:

```
$ vips pdfload
load PDF with libpoppler
usage:
   pdfload filename out
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   flags        - Flags for this file, output VipsForeignFlags
   disc         - Open to disc, input gboolean
			default: true
   access       - Required access pattern for this file, input VipsAccess
			default: random
			allowed: random, sequential, sequential-unbuffered
   page         - Load this page from the file, input gint
			default: 0
			min: 0, max: 100000
   dpi          - Render at this DPI, input gdouble
			default: 72
			min: 0.001, max: 100000
   scale        - Scale output by this factor, input gdouble
			default: 1
			min: 0.001, max: 100000
```

Or docs here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsForeignSave.html#vips-pdfload

**Comment by jcupitt** [comment]
Actually, now I look at your command, you don't need the `density` option. The `vipsthumbnail` in 8.3 knows about PDF and will directly render it at the size you request. Try:

```
vipsthumbnail file.pdf[page=1] -o file.jpg[background=255] --size=1920
```

It should look nice.

**Comment by asgerb** [comment]
@jcupitt Thanks for the super quick replies!

Weirdly it looks great locally in OS X, but on a VPS running ubuntu it's very pixelated. Will investigate!

**Comment by asgerb** [comment]
OK, so it seems `pdfload` is not working on the Ubuntu install:

````
$ vips pdfload
vips: unknown action "pdfload"
```

Although it seems to have the newest version:

```
$ vips --vips-version
libvips 8.3.3-Mon Sep 12 04:40:24 EDT 2016
```

**Comment by jcupitt** [comment]
Did you build libvips yourself? If you did, try configuring again and checking the output. You need the lines:

```
PDF import with poppler-glib: 		yes
  (requires poppler-glib 0.16.0 or later)
```

in the final summary.

**Comment by asgerb** [comment]
Indeed I did build it and am trying to reconfigure now. Although I'm not sure which `poppler` package to install on Ubuntu 14.04 to make it work:

```
checking for POPPLER... no
configure: WARNING: poppler-glib >= 0.30.0 or cairo >= 1.2 not found; disabling PDF load via poppler
```

Tried; `libpoppler-dev`, `libpoppler-glib-dev` and `poppler-utils` so far.

**Comment by jcupitt** [comment]
It may be too old, 14.04 is getting on a bit. You might find you need to build poppler as well. 

I see:

```
$ vipsthumbnail ISO_12233-reschart.pdf -o x.png --size 512
$ pkg-config poppler-glib --modversion
0.41.0
```

![x](https://cloud.githubusercontent.com/assets/580843/18471227/c4c4319a-79a8-11e6-9d00-69eaf6821a49.png)

**Comment by jcupitt** [comment]
Or of course you can run the thing in docker. It's almost as fast and you won't need to start replacing parts of your server.

**Comment by asgerb** [comment]
Yay, now it works! I built `poppler` from source and configured with the following command: `./configure --enable-poppler-glib`, then reinstalled `libvips`. Now it correctly locates poppler and PDF thumbs are sharp and beautiful. Thanks a ton @jcupitt!

**Comment by jcupitt** [comment]
Great!
