### ISSUE TITLE
Rank function allows neither 0 nor the number of window pixels as index argument

### ISSUE THREAD

**Issue by erdmann** [jcupitt/libvips#555]
It appears that the rank function limits its arguments too much (or I am not understanding its functionality).

```
$ vips --version
vips-8.4.1-Sat Oct  8 13:04:04 CEST 2016

$ vips rank
rank filter
usage:
   rank in out width height index
where:
   in           - Input image argument, input VipsImage
   out          - Output image, output VipsImage
   width        - Window width in pixels, input gint
			default: 11
			min: 1, max: 100000
   height       - Window height in pixels, input gint
			default: 11
			min: 1, max: 100000
   index        - Select pixel at index, input gint
			default: 50
			min: 1, max: 100000000
```

Consider the cases of constructing moving minimum and moving maximum filters with the `rank` function.
If I understand correctly, the rank filter moves a window over the image, and at each (non-edge) position the window contains `width*height` pixels.  This collection is sorted and then a pixel is selected from the sorted list with the `index` argument.  The indexing scheme for `index` is presumably either 0-based or 1-based.  In those cases, I expect the following in the case of a 5x1 window:

In the 0-based indexing scheme:
  5x1 moving min filter:  `vips rank in.v out.v 5 1 0`
  5x1 moving max filter:  `vips rank in.v out.v 5 1 4`

In the 1-based indexing scheme:
  5x1 moving min filter:  `vips rank in.v out.v 5 1 1`
  5x1 moving max filter:  `vips rank in.v out.v 5 1 5`

However, vips prevents both 0 and the number of window pixels in the `index` argument:
```

$ vips rank in.v out.v 5 1 0
(vips:25492): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'index' of type 'gint'
rank: parameter index not set

$ vips rank in.v out.v 5 1 5
rank: index out of range

```

Am I misunderstanding the way the rank function works?  Additionally (and possibly related), how does rank work when it reaches the edge of an image?  If the window falls off the edge of the image, are there still considered to be `width*height` pixels in the window?  How does one specify `index` for "the highest (lowest) pixel in the window, even if the window is truncated?"  And finally, if it is indeed edges that are causing the problem, what is the recommended way to construct a moving min/max filter?

Many thanks in advance.

**Comment by jcupitt** [comment]
Ooop! Oh dear, you're right, it should allow `index == 0`, sorry about that. I've committed a change, thanks very much for reporting this.

The rank docs are here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-morphology.html#vips-rank

So, yes, it's zero based, the metadata on the argument was wrong.

For image edges, the input image is expanded by copying edge pixels.

**Comment by jcupitt** [comment]
That wasn't very clear re. edge pixels. Suppose you want to pass a 5x5 window over a 100x100 pixel image. vips will add two extra pixels all around your input image, made by copying edge pixels either horizontally or vertically. The corners are filled with the value of the corner pixels in the input image.

Now the 5x5 window is moved to every complete 5x5 position in the expanded input image and the rank calculated, producing an output image the same size as the original input image.

vips has a variety of tricks to make expanding the input image efficient, every for very large images. It's done by this operator:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-embed

It supports a range of edge extension strategies (black, white, mirror, tile, copy), but everything just uses copy, since it (usually) works very well.

**Comment by erdmann** [comment]
Many thanks for the fast fix and the very clear explanation, John.
