### ISSUE TITLE
vips warning when loading tiff image

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#586]
Hi,

I'm using vips 8.4 C API on Windows 64bit OS. When I call `vips_image_new_from_file` to load a .tif file I get the following console warning message from vips :

> vips warning: tiff2vips: no resolution information for TIFF image "\\t5810\ShoshanFileServer\Cases\22-Jan-2017\138\107\8
> 70\Scan\Frame_42\42_0-RgbCombined.tif" -- defaulting to 1 pixel per mm

Is it right to process those images given this warning status on them? Generally, I'm stitching those .tif files and then build DZ pyramid from the whole stitched image? 

If it is just to inform the user about potential implications, can I suppress those messages?

Thanks

**Comment by jcupitt** [comment]
Hi @alonit, yes, the warning is there because all vips images have a resolution attached to them, but not all TIFFs do. If you load a TIFF without any resolution info, vips has to invent some, so the warning is that the resolution on this image is probably bogus. 

You can suppress vips warning messages by defining the environment variable `VIPS_WARNING`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-error.html#vips-warn

**Comment by alonit** [comment]
OK, Thanks

**Comment by jcupitt** [comment]
OK, I'll close then.
