### ISSUE TITLE
About vips_image_wio_input performance

### ISSUE THREAD

**Issue by almosnow** [jcupitt/libvips#613]
Hey there,

I wrote a small utility (using the C++ API) that transforms images using libvips, so far it's doing good and I'm very impressed by the overall performance of the whole library. Cheers to that 😄.

I perform a couple baked in transformations and then some custom algorithms that read the raw pixel data (via vips_image_wio_input).

When benchmarking my program, I've noticed that the vast majority of time is spent on this routine. To give you an idea, my whole pipeline takes around 190ms/image and vips_image_wio_input takes a good 160ms of that. Also, it only takes as long the first time it gets called. Subsequent calls to vips_image_wio_input take 1ms or so, even when called on different VipsImage* objects.

I haven't checked out the source but my gut tells me it may be related to time spent allocating memory. But I have no idea, I'm very interested in this because if I can avoid the time spent in there, I would reduce my total processing time to around 30ms and that would be absolutely mind blowing.

**Comment by jcupitt** [comment]
Hi @almosnow. When vips executes `vips_image_wio_input()`, it allocates a large chunk of memory (as you say) and then renders the image into it. This will trigger all the earlier stages of computation, including image load. So I'd guess the 160ms is anything you've used vips for, rather than memory allocation.

If you can post your code I'd be happy to have a look and see if I can speed it up. I usually use https://gist.github.com/
