### ISSUE TITLE
Question about possible issues with VIPS region caching

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#616]
In my application I am using ```vips_region_new()``` and ```vips_region_prepare()``` "by hand" in order to cache pre-computed  image data in the background.

This cannot be done with the ```vips_sink_*()``` kind of functions because I need to be able to stop the processing at any time when the pipeline is modified.

However, it seems that some recent changes introduced in the 8.4.* series of releases somehow broke my code, and this seems to be related to the way VIPS handles region caching for non-worker threads.

The current git master branch provides a working solution again, and if I understand correctly this is because region caching has been finally completely disabled for non-worker threads.

Hence my question: is the current solution implemented in git master to be considered a "long-term" one? Or should I try to modify my code such that it uses the ```vips_sink_*()``` family of functions for better compatibility with different VIPS versions?

Thanks!

**Comment by jcupitt** [comment]
Hi Andrea, 

You might be able to use `vips_sink_*()`, it has a stop early mechanism. The function you pass to the sink has this prototype:

```C
static int 
vips_statistic_scan( VipsRegion *region, void *seq, void *a, void *b, gboolean *stop );
```

If you set `*stop` to `TRUE`, iteration will stop early with no error. Things like `vips_max()` use this --- for example, if you `vips_max()` on a uchar image and it sees a 255, it'll stop immediately and won't process the whole image. 

There's also `vips_image_set_kill()`, which will make everything connected to an image fail immediately with an error, but that's much less useful, and should maybe be removed. 

And of course you can just unref an image with a running `vips_sink_screen()` and it should shut everything down. It can't force quit worker threads, but it'll stop issuing new work units, and return as soon as the final worker exits. 

Yes, the git master code is supposed to be the new way of doing things. As you say, no caching for non-workers, since there's no reliable way to spot when they fall out of use. It'll be vips8.5, due RSN.

**Comment by aferrero2707** [comment]
Thanks for the quick answer! I will keep the current code for the moment, but I will try the ```vips_sink_*()``` solution whenever I will have the possibility... good news that the current git version is a long-term solution!
