### ISSUE TITLE
Question: 32-bit float to PNG issues, cont'd...

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#618]
Relates to #534. I'm still having issues creating a PNG out of a [float 32 file](https://github.com/jcupitt/libvips/files/837320/ct-test-1024x1024x1-f32.raw.zip).

I'm using the Ruby API so forgive the code, but this is what I'm doing:
```
image = Vips::Image.rawload(file, 1024, 1024, 4)
image = image.copy(bands: 1, format: Vips::BandFormat::FLOAT, interpretation: Vips::Interpretation::MULTIBAND)
image = image.colourspace(Vips::Interpretation::GREY16)
```

I've also tried using `image = image.cast(Vips::BandFormat::USHORT)` and even `image = image.scale()` but it comes out as all white or all black or a severe loss of contrast.

At this point, I feel I'm just doing random stuff.

I presume it is -- as you suggested previously -- a colourspace issue but I can't for the life of me work out what I'm doing wrong.

Regards,

Simon

**Comment by harukizaemon** [comment]
OK so I tried using `vips scale` and it worked fine. I then used `Image::scale` and it looks like it has a bug. Shall report over on the ruby project.

**Comment by jcupitt** [comment]
Hi Simon, I had a look at your image, it's a one-band float with pixels in the range 4000 - 25000, so in vips terms, grey16 (16-bit ushort) looks like the best fit. 

You could write a converter like this:

```ruby
#!/usr/bin/env ruby

require 'vips'

image = Vips::Image.rawload(ARGV[0], 1024, 1024, 4)
image = image.copy(bands: 1, format: "float", interpretation: "grey16")
image = image.cast("ushort")
image.write_to_file ARGV[1]
```

Then:

```
$ ./topng.rb ct-test-1024x1024x1-f32.raw x.png
```

Gives:

![x](https://cloud.githubusercontent.com/assets/580843/23850921/670519e2-07d9-11e7-8747-464114a5deb8.png)

It looks a little dark, since grey16 is 0 - 65535, but the data is there. You can see some details if you squint a bit.
