### ISSUE TITLE
guetzli: Google Perceptual JPEG encoder

### ISSUE THREAD

**Issue by asilvas** [jcupitt/libvips#623]
Any chance in getting adoption? https://github.com/google/guetzli/

**Comment by lovell** [comment]
Hi Aaron, Guetzli currently provides a command line tool rather than a shared library that libvips could be compiled against.

If you've already tried it you've probably noticed the high levels of CPU and RAM consumed :(

We might be able to borrow some of its preprocessing tricks though - see https://github.com/lovell/sharp/issues/427

**Comment by asilvas** [comment]
Thanks for the (very) fast reply! Ok, good to know it's been looked at. Sounds like it might not be a good fit for fast (on-the-fly) encoding, even if it were consumable as a shared library. Hopefully it can be optimized enough in the future to be usable, or its techniques rolled into another encoder.

By the way, we use libvips to process billions of image requests. You've done incredible work, thank you!
