### ISSUE TITLE
vips_thumbnail(...) : thumbnailing to different output size / output format in a single call

### ISSUE THREAD

**Issue by yaourt** [jcupitt/libvips#656]
This is an ehancement proposal to vips_thumbnail(...) : from the same input image, and a single disk read, thumbnails this input image to different output size, output format, quality etc.

I'm seeing (at least) two ways of doing it:

1. Allows vips_thumbnail(....) to take as input a VipsImage already read by another mean and delegates all the "logic" to the caller

2. Implement this logic directly into vips_tumbnail(...)

My concrete goal here is to resize the same input image to various output sizes and for each output size, store the result as a JPEG and WEBP file.

Right now, I'm doing this by:
- sorting the desired output size (w x h) descending
- first processing the biggest output size using vips_thumbnail(...), (resizing to w x w or to h x h, using the biggest)
- storing the result of the previous operation into a buffer (TIFF, uncompressed)
- processing then this buffer for all the desired output size / output format

With Option 1), the intermediate buffer could be avoided, and a VipsImage used instead.
With Option 2), everything could be avoided ;-)

Or perhaps, everything is already there, I just missed it ?

What do you think ?

**Comment by jcupitt** [comment]
Hi, this has been discussed a bit with sharp. 

At least with jpeg input files, there may not be much to be gained by reusing results, since a lot of the speed comes from libjpeg's shrink-on-load feature. If you are loading the source image at different sizes, there are no computations to reuse. 

In this case, something like GNU parallel will be quicker. For example:

```
parallel vipsthumbnail wtc.jpg -s {} -o wtc_{}.jpg ::: 1024 512 64
```

To make three thumbnails at once. Formats like SVG or PDF which have even more flexible loading work better still in this way.

For PNG, there is a possible win from reusing results since PNG load is so slow. However, PNG load is also single-threaded, so if you have (for example) a four core machine and you want to make four thumbnails, it'll actually be quicker to decode the full image four times in parallel. Your CPU use will be much higher, but your latency will be lower.

**Comment by jcupitt** [comment]
Ooops, didn't mean to press comment so soon, sorry.

Anyway, I agree that something like `vips_thumbnail_image()` would be useful for people who want to reuse shrinks, or have a non-file or memory source. I'll have a look.

**Comment by yaourt** [comment]
I'll be happy with such `vips_thumbnail_image()` !

Thanks
And btw, you are doing a great job with this lib, thanks for your work and this neat piece of software !

**Comment by jcupitt** [comment]
OK, in master, it was very simple, just another subclass of `thumbnail`.

Thanks for suggesting this!

**Comment by jcupitt** [comment]
I had a go at a tiny program to use repeated subsampling to make thumbnails:

```python
#!/usr/bin/env python

import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

filename = sys.argv[1]

widths = [int(x) for x in sys.argv[2:]]
widths.sort()
widths.reverse()

# make the first thumbnail from the filename ... this will exploit
# any shrink-on-load features in the file format loader
image = Vips.Image.thumbnail(filename, widths[0])

# this will allocate a memory buffer and render the thumbnail into that
image = image.copy_memory()

image.write_to_file(str(widths[0]) + "_" + filename + ".jpg")

for width in widths[1:]:
    image = image.thumbnail_image(width)
    image = image.copy_memory()
    image.write_to_file(str(width) + "_" + filename + ".jpg")
```

On my laptop, with a 10k x 10k pixel source image, I see:

```
$ time ./manythumb.py x.jpg 4096 1024 512 256 128
real	0m1.974s
user	0m3.412s
sys	0m0.112s
```

With parallel I see:

```
$ time parallel vipsthumbnail x.jpg -s {} -o {}_x.jpg ::: 4096 1024 512 256 128
real	0m1.878s
user	0m5.172s
sys	0m0.156s
```

So it's slightly slower, but there is a drop in CPU use overall.

With a 10k x 10k PNG it looks better, since you save the repeated PNG decode:

```
$ time ./manythumb.py x.png 4096 1024 512 256 128
real	0m4.587s
user	0m5.808s
sys	0m0.116s
$ time parallel vipsthumbnail x.png -s {} -o {}_x.jpg ::: 4096 1024 512 256 128
real	0m10.513s
user	0m26.228s
sys	0m0.344s
```

**Comment by yaourt** [comment]
More than perfect, thanks !

Any chance to have this `vips_thumbnail_image()` int the upcoming v8.5.5 ?

**Comment by jcupitt** [comment]
Sorry, micro versions are just for bugfixes, API changes go in minor versions, so it'll be 8.6. 

You can subclass vips operators in your own code, so you could copy-paste that bit of C into your stuff somewhere and it'd all be linked on at runtime when you init it. You should change the prefix from `vips_` to `my_` (or something like that) to avoid name clashes.

**Comment by yaourt** [comment]
Ok, clear.

Thanks again for all our work
