### ISSUE TITLE
Grayscale

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/libvips#685]
Does libvips provide any out of the box support for determining if an image is grayscale, black and white, or monochrome?

**Comment by jcupitt** [comment]
Hi, images are always 0 for black and 255 (or 65535, or 1.0, depending on the colourspace) for white. When you write, you can ask the writer to code the file as one bit or inverted if you wish. 

Are these TIFFs? `tiffinfo` is the best thing for looking inside TIFF files.

**Comment by bubba-h57** [comment]
Yes sir, assume they are all tiff files. 

My goal is to determine the best possible transformation prior to tiling them. Where best is both the most efficient file and image size. 

We have a lot of huge blueprints, the majority of which are simply black/white or grayscale. However, we get a handful of color images mixed in. I am trying to determine the optimal max image size (that I can scale down to) for zooming. If the image is color, then I do not want to scale it down, just tile the original. But if it is black and white, do I really need more than X levels to zoom into inspect it?

I still haven't determined what X should be, if you have any suggestions.

**Comment by jcupitt** [comment]
With `dzsave` you really have to use jpg or png as the tile format, so you can't do better than 8 bits per pixel. So greyscale / b&w / mono are all the same. 

Do you mean the raster size to render the PDF at before dzsave? I'd be tempted to just pick 600 dpi and say that's enough for anyone. If you find you are missing detail on some images it'll be because they haven't been saved with the correct resolution.

**Comment by bubba-h57** [comment]
Thanks!
