### ISSUE TITLE
Multiple runs of stats() resulting in different min X Y and max X Y values

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#713]
I am implementing the `stats` function in sharp. While writing a few test cases, to validate the stats output, I found out that the values for min and max X,Y coordinates (the last 4 columns of stats) changed with every test run. Is this a known acceptable behaviour?

The example image - https://github.com/lovell/sharp/blob/master/test/fixtures/2569067123_aca715a2ee_o.jpg

I get a min X value on red channel as 128 or 215 on multiple test runs.

**Comment by jcupitt** [comment]
Hello, this is expected behaviour. 

If there is more than one min, you can't tell which thread will find it first, so it'll randomly pick one of them.  The coordinates are of **a** image minimum, not **the** image minimum.

There's a note about this behaviour in `vips_min()` and `vips_max()`, though perhaps it should be in stats as well.

http://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-min

**Comment by lovell** [comment]
If the thread count is `n`, would `size=n` minima be expected to include the image minimum?

**Comment by jcupitt** [comment]
It'll always include the image minimum, it changes which one you see. 

It only happens for things like uchar where there is a definite known-in-advance minimum possible value. As soon as stats (or `vips_min()`) sees a zero, it can stop searching since it knows there can be nothing lower.  This can be an important optimisation in some cases.

So which minimum it reports depends on which thread finds a zero first, which will vary each time you run.

Solutions:

1. Set concurrency to 1. With only one thread, you can't get a race to zero.

2. Test with something other than uchar, for example float. If there's no known-in-advance minimum, vips will have to keep searching. 

3. Use a test image with a single zero in. You could add 1 to one of your test images (for example), then set a single zero somewhere and confirm that stats finds it. This is what the vips test suite does (I think).

**Comment by jcupitt** [comment]
Ooops, I just read the stats source. 2) will work for `vips_min()`, but not `vips_stats()`. Min has some extra code to report the leftmost / uppermost minimum. 

The vips test suite doesn't test min/max position of `vips_stats()` output, though it does test `vips_min()`

**Comment by lovell** [comment]
Sorry, ignore my misunderstanding (my brain is in summer holiday mode), thanks for the clarification John.

**Comment by rnanwani** [comment]
Thanks for the explanation @jcupitt . While we are on `stats` found a case where the output from `libvips` doesn't match that with the output from `identify`.

Image: 

Output from vips stats (gray + alpha):
```
{      min: 0,
       max: 101,
       mean: 50.5,
       stdev: 71.4177848998413
}, {
       min: 0,
       max: 255,
       mean: 127.5,
       stdev: 180.31222920256963,
}
```

Output from `identify`
```
Gray:
      min: 101 (0.396078)
      max: 255 (1)
      mean: 178 (0.698039)
      standard deviation: 108.894 (0.427037)
      kurtosis: -2.75
      skewness: 0
      entropy: 1
    Alpha:
      min: 0 (0)
      max: 255 (1)
      mean: 127.5 (0.5)
      standard deviation: 180.312 (0.707107)
      kurtosis: -2.75
      skewness: 0
      entropy: 1
```

The image contains only two pixels of colours which are `(101,101,101,255)`  and `(255,255,255,  0)` as reported by `identify`. Probably, the transparent pixel is treated as `(0,0,0,0)` in vips `stats`.

**Comment by jcupitt** [comment]
I made a couple of grey + alpha test images: `101.png` is [101, 255] in each pixel, `255.png` is [255, 0] in each pixel:

![101](https://user-images.githubusercontent.com/580843/29366807-f3e6ad06-8292-11e7-8301-7a8543303b8b.png)
![255](https://user-images.githubusercontent.com/580843/29366808-f3edac00-8292-11e7-8c61-1c3cf2533486.png)

I see:

```
$ vips stats 101.png x.csv
$ more x.csv
101	255	1.45818e+06	3.08126e+08	178	77.0047	0	10	0	10
101	101	413696	4.17833e+07	101	0	0	10	0	10
255	255	1.04448e+06	2.66342e+08	255	0	0	10	0	10
```

Which is a little hard to read, but it's calculating an average of 178, which of course is `(101 + 255) / 2`. identify reports 101, so it's multiplying the alpha in. 

For the other PNG, I see:

```
$ vips stats 255.png x.csv
$ more x.csv
0	255	1.04448e+06	2.66342e+08	127.5	127.508	0	8	0	8
255	255	1.04448e+06	2.66342e+08	255	0	0	8	0	8
0	0	0	0	0	0	0	8	0	8
```

ie. a mean of 127.5, which is `(0 + 255) / 2`.

**Comment by jcupitt** [comment]
I'll close, please reopen if you still have problems.
