### ISSUE TITLE
Zoomable Image Viewer List

### ISSUE THREAD

**Issue by Warren-GH** [jcupitt/libvips#716]
I don't know if this is the proper place for this, so apologies if it is not. 

I have only recently begun using VIPS to generate very large stitched images, which it seems to do well. However, it would be great if there was a list of applications capable of opening the different types of 'zoom' images that VIPS supports and their limitations somewhere in the VIPS documentation. A lot of viewer projects seem to mention VIPS as being capable of generating images, but not the other way around.

From my very limited testing (on Windows only), I have found the following:

1. **DZI** :  OpenSeaDragon (only one I tested, works OK even up to 400k x 400k resolution), ...
2. **DZI in ZIP**: None?? (I assume something has to open this or it wouldn't be an option? It would be fantastic if someone can point me to something because this takes about 5 hours off of the image generation time, and it is much faster to delete a single file than the millions that are generated without ZIP)
3. **Pyramidal TIF**: Windows Image Viewer, Irfanview, IIPImage + IIPMooViewer, seemingly everything that supports the TIFF standard
4. **Pyramidal TIF w/BIGTIFF**: Irfanview 64-bit up to somewhere around 60k x 60k resolution, crashes on anything higher, (nothing else above seemed to work with bigtiff flag, including IIPImage, which supposedly supports bigtiff as mentioned in their [documentation](http://iipimage.sourceforge.net/documentation/images/) in the VIPS section).

(I've tested no other formats thus far)

Thanks for any input or clarification on this.

**Comment by jcupitt** [comment]
Hello Warren,

2. I know quite a few people who've implemented this but I don't know many who've made their work publicly available. It's not that hard: you add some JS to the viewer to read the index out of the tail of the file using http resume, then seek and fetch each tile (again, with resume).

The dzi-in-zip mode was added to help Windows, since large directory trees cause awful performance problems there, as you noted. Martin Weihrauch has done some work on this and released a Windows viewer and a PHP tile server so that you can view them on an unmodified seadragon client:

https://lists.andrew.cmu.edu/pipermail/openslide-users/2015-November/001147.html

He might be able to help.

You can mitigate the performance hit somewhat by disabling your virus checker, the desktop indexing service, and short filename generation. The last one is very important for large directories, but you might need to reformat your HDD (I think), since short-filenames-off only became the default some time post Vista.

4. There's also nip2, the vips GUI, which can manipulate these images. There's a Windows build too:

https://github.com/jcupitt/nip2/releases

It doesn't use the pyramidal structure, unfortunately, so it's a little slow at zooming out, but it does work. Being able to manipulate the images (rotate, sharpen, colour change, whatever) can be useful too.

I'm surprised iipimage fails with bigtiff, I thought Ruven added that ages ago. It might be worth asking him if there's a more recent version.
