### ISSUE TITLE
vips fails with very high resolution SVGs

### ISSUE THREAD

**Issue by brewin** [jcupitt/libvips#732]
Running `vips dzsave` on the following SVG files, the first one works as expected but the second one results in blank tiles.

```svg
<svg height="5000" width="5000">
    <circle cx="2500" cy="2500" r="2000" stroke="black" stroke-width="50" fill="red" />
</svg> 
```

```svg
<svg height="50000" width="50000">
    <circle cx="25000" cy="25000" r="20000" stroke="black" stroke-width="50" fill="red" />
</svg> 
```

**Comment by lovell** [comment]
There are similar reports at https://github.com/lovell/sharp/issues/715

**Comment by jcupitt** [comment]
Hello, the SVG loader works like this:

1. On initial load, the SVG file is parsed into memory. Files which include embedded JPG images probably decode the entire JPG to a memory buffer at this point (though I'm not certain). libvips gets the metadata (width, height, etc.) from the parsed SVG. 

2. To handle pixel requests, libvips uses a linecache, with tiles as wide as the image and 128 pixels high. I think there will usually be 3 or 4 tiles in the cache. Each tile is filled by one call to svg render, so it's relying on librsvg to efficiently cull bits of the SVG which don't touch the tile (it seems pretty good at this). If embedded JPG images are decoded at this stage, you can expect appalling performance, since the whole image would be decoded for each tile.

It sounds like the 50,000 x 128 pixel tiles are triggering some librsvg limit. Perhaps we should split horizontally as well, perhaps into 10,000 pixel chunks? It would be a simple change.

**Comment by jcupitt** [comment]
I made a slightly smaller test-case. This works fine:

```
$ cat >circle30.svg
<svg height="30000" width="30000">
    <circle cx="15000" cy="15000" r="15000" stroke="black" stroke-width="50" fill
="red" />
</svg> 
^D
$ vips copy circle30.svg x.v
```

```

This just writes a black image:

```
$ cat >circle40.svg
<svg height="40000" width="40000">
    <circle cx="20000" cy="20000" r="20000" stroke="black" stroke-width="50" fill
="red" />
</svg> 
^D
$ vips copy circle40.svg x.v
```

**Comment by jcupitt** [comment]
Oh hehe, of course, 32767 works fine, 32768 fails. I'll see if limiting the tile size helps.

**Comment by jcupitt** [comment]
Yes, seems to have fixed it, I can now render a 40k pixel circle successfully. Thanks for reporting this!

It won't help with SVGs containing huge embedded JPG images, that's a difficult case to handle well.
