### ISSUE TITLE
Improve GObject instrospection annotations

### ISSUE THREAD

**Issue by astavale** [jcupitt/libvips#741]
#740 is a small test of updating the annotations for a function in libvips. This is to improve the Vala bindings to libvips, but that PR needs to be checked to find that it doesn't upset any other language bindings.

Given that any G-I annotation changes will be across many files it is probably best to outline what impact is acceptable:

### Out parameters 
Out parameters are used extensively in libvips. By adding `(out)` to the docblock the GIR (GObject Introspection Repository) is generated with the relevant metadata. This change is minimal and will hopefully have no impact on the other bindings such as Python.

An example annotation is:
`@pixel_average: (out): output pixel average`

### Methods
An example function is `avg`. Currently this takes an `Image` as a parameter, but really this is an instance parameter. By adding the `(method)` annotation the GIR is generated with this additional metadata. 

This does significantly change the API because a function is no longer static, so no longer requiring an explicit instance argument to be passed. For example `Vips.avg( my_image, out pixel_avg )` becomes `my_image.avg( out pixel_avg )`.

An example annotation is:
```
vips_avg: (method)
@in: input #VipsImage
```

### Variadic arguments
While the GIR will contain the details of variadic arguments, the GIR will add `introspectable="0"` to the metadata because GI does not support variadic arguments at the current time.

For Vala bindings this means some small additional work by adding Vala specific metadata when generating the VAPI. For other bindings the function may not be included because of the `introspectable="0"` attribute. This is probably a question of API design and how much benefit variadic arguments bring.

### Use of GError
This also relates to #707 and the comments made in the related lovell/sharp issue.

The use of GError enables `try...catch` blocks in Vala (`try...except` in Python). At the moment a lot of functions in libvips return an `int` to signal if the function has worked. This means an out parameter needs to be used to get the value. The API would be easier to use from higher level language bindings if the function returned the value and raised a GError if the function failed. GError also allows for additional details to be returned, including text.

Clearly any switch to GError is a major breaking change in API for libvips.

### Is GIR worth it?
GIR brings a large number of possible bindings, see [Languages Binding with GObject-Introspection](https://wiki.gnome.org/Projects/GObjectIntrospection/Users). Although they are in various states of usefulness.

I understand the [Haskell generator](https://wiki.haskell.org/GObjectIntrospection) is very good. Both the [Go generator](https://github.com/linuxdeepin/go-gir-generator) and [Ruby generator](https://github.com/mvz/gir_ffi) are active, having commits for 2017.

From my own perspective, having libvips available from Vala/Genie is useful. A quick image processing library would be great.

**Comment by jcupitt** [comment]
Hello again Al,

Sure, let's add more annotations. The annotations on things like `vips_avg()` are there for gtk-doc rather than language bindings, since (as far as I know) none of them use this layer of libvips. I can see that they could help Vala, so I'm all for it.

The libvips C API is tricky to bind because of the heavy use of varargs (as you say). The Python, Ruby, Lua, PHP, C++ and JavaScript bindings (and I suppose the command-line) all use the layer down from that.

The lower level libvips API is something like:

```C
VipsOperation *op = vips_operation_new("avg");
g_object_set_property(op, "in", input_image);
if (vips_operation_build(&op)) { ... error }
g_object_get_property(op, "out", &average);
g_object_unref(op);
```

ie. a straightforward [new / set / build / get] structure with no varargs. The C API is built on top of this as well, you probably saw.

Because they work at this lower level, these bindings can use the keyword argument features of these languages instead of varargs. For example in node.js you can write:

```javascript
image = image.embed(10, 10, 100, 100, {extend: 'copy', background: [128, 255, 0]});
```

For Vala, I think I would write a short wrapper (100 lines of code?) which used new / set / build / get to make any libvips operation callable in a nice way, then I would write a generator which printed tiny wrappers for each of the operations.

For example, the C++ API defines `call()`, which can call any libvips operation with a set of options:

https://github.com/jcupitt/libvips/blob/master/cplusplus/VImage.cpp#L513

Then a scrap of Python generates wrappers like this:

https://github.com/jcupitt/libvips/blob/master/cplusplus/vips-operators.cpp#L315

Perhaps you could map libvips operation options to Vala's optional argument feature. 

On your points:

##  `out` and `method` annotations

Sure, let's add these, I don't think they will break anything, since this layer of libvips is not used by any current language binding. 

## varadic functions

In my opinion, the solution here is not to use the C API in libvips, it's very difficult and annoying from other languages. You can map operation arguments to something better in the calling language. 

## GError

The libvips bindings all look for the int return from `vips_operation_build()` (in the new / set / build / get API) and use that to raise an exception. It seems to work well.

## Is GIR worth it?

Sure! It's very convenient. I'd use it to call the new / set / build / get API.

In fact I've started moving away from GIR recently. libvips actually has a pretty small API, only about 30 functions in total, so GIR does not save a huge amount of effort. It's not much more work to just use FFI and call into the libvips shared library directly. And doing it yourself with FFI has a lot of significant advantages, there are some notes here:

https://github.com/jcupitt/pyvips/#background

**Comment by jcupitt** [comment]
Oh, and here's the main function of the varargs interface to libvips:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/operation.c#L843

But I think that maybe wouldn't help Vala. 

What would your ideal API look like? libvips operations have five main types of argument:

* Required input (for example, `in` for `avg`), there can be zero or more of these.
* Required output (for example `out` for `avg`), there can be zero or more. Many operations only have one, but there are quite a few that will always produce two or more, for example `vips_profile()`.
* Optional input, for example 'extend` of `embed`. There can be a lot of these, for example `tiffsave` has 17, crazily. I hope that says more about the TIFF format than libvips.
* Optional output. Many operations set extra outputs which you can get if you wish, for example you can get the position of the maximum pixel from `max` if you wish.
* Modified input. libvips always returns new images rather than modifying input images, since it's a streaming library. However, it contains a set of paintbox functions which really do modify their inputs, for example `draw_circle`. These need special handling in some languages. 

I'm not sure how best to expose that lot to Vala. Perhaps varargs is the correct solution.

**Comment by jcupitt** [comment]
I've bumped into a problem with some of the changes to `iofuncs/object.c`: they seem to have broken the GOI Python binding.

For example, the `(method)` annotation on `vips_object_argument_isset()` seems to stop Python from finding the method on objects:

```
john@mm-jcupitt5 ~/GIT/libvips (master) $ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Vips', '8.0')
>>> from gi.repository import Vips, GObject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 615, in <module>
    class Image(Vips.Image):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 1056, in Image
    @add_doc(generate_docstring("ifthenelse"))
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 530, in generate_docstring
    args = op.get_args()
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 254, in get_args
    args = [Argument(self, x) for x in self.props]
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 197, in __init__
    self.isset = op.argument_isset(self.name)
AttributeError: 'VipsIfthenelse' object has no attribute 'argument_isset'
>>> 
```

`op` here is a `VipsOperation`, which is a subclass of `VipsObject`, which should have `argument_isset` as a method. I'm not quite sure where this method has moved to. 

For now, I've removed three `(method)` annotations from object.c, this seems to be enough to get the binding working again.

**Comment by jcupitt** [comment]
This seems to be finished, I'll close. Please open a new issue if there are problems with 8.6.
