### ISSUE TITLE
Unexpected rotation in libvips

### ISSUE THREAD

**Issue by kylemacfarlane** [jcupitt/libvips#772]
I have an image which when I open in Photoshop, Chrome, etc it appears in the correct orientation but opening and saving the image through libvips rotates it 90 CW.

`vipsheader` says it has the following orientation tags:

```
exif-ifd1-Orientation: 6 (Right-top, Short, 1 components, 2 bytes)
orientation: 6
```

If I update the orientation tags with `exiftool -Orientation=6 -n image.jpg` I then get the following output from `vipsheader`:

```
exif-ifd0-Orientation: 6 (Right-top, Short, 1 components, 2 bytes)
exif-ifd1-Orientation: 6 (Right-top, Short, 1 components, 2 bytes)
orientation: 6
```

Now Chrome, Photoshop, libvips, etc all rotate the image the same way.

So it would seem that most apps only read `exif-ifd0-Orientation` but libvips will search for any orientation tag? Is it safe to do something like the following or will this create even more problems:

```
for f in image.get_fields():
    if f.lower().endswith('orientation') and f != 'exif-ifd0-Orientation':
        image.remove(f)
```

**Comment by kylemacfarlane** [comment]
Are EXIF tags case sensitive? What would happen if there's a `exif-ifd0-orientation` but no `exif-ifd0-Orientation` tag?

I tried to test with pyvips but couldn't figure out how to set metadata without type errors.

**Comment by jcupitt** [comment]
Hello, that's right, libvips will use the first orientation tag it finds. ifd1 is usually the embedded thumbnail and if0 is the actual image, but not always. I've come across images which use ifd1 for image orientation.

Maybe things are more stable now. If Chrome is fixing on ifd0 that probably means libvips should as well -- what do you think?

libvips handles orientation like this:

1. On JPEG read, it decodes the exif block and searches for orientation tags. The first one is used to set the `orientation` metadata on the image (it's just an int).

2. Operations like `autorot` don't look for exif tags, they check for the `orientation` metadata item. This is because other formats, like TIFF, also support orientation, and `autorot` has to work with them as well.

3. On JPEG write, it rebuilds the exif block, then uses the value of the `orientation` tag to set the value of oriention tag on ifd0.

So from Python, you can do:

```python
a = pyvips.Image.new_from_file(sys.argv[1])
a.set('orientation', 5);
a.write_to_file(sys.argv[2])
```

To set (or change) orientation.

**Comment by jcupitt** [comment]
You can use `vipsheader -a x.jpg` to see all the tags that libvips knows about on an image, it's handy for debugging.

**Comment by jcupitt** [comment]
Oh, sorry, you have that already, never mind.

**Comment by jcupitt** [comment]
So to answer your question, as a work-around I would suggest this after load:

```python
try:
    orientation = image.get('exif-ifd0-Orientation')
    image.set('orientation', int(orientation.split()[0]))
except:
    image.set('orientation', 0)
```

ie. just set orientation from ifd0; otherwise, reset to 0.

**Comment by kylemacfarlane** [comment]
Thanks for the help. BTW is there a way to pass an image instance straight into `thumbnail_from_buffer()` without having to first write it back to a buffer (which presumably has some overhead)?

**Comment by jcupitt** [comment]
8.6 adds `thumbnail_image`, which will thumbnail any image instance:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L1043

but 8.6 is still not quite done :( Another week or two, hopefully.

What do you think about insisting on ifd0?

**Comment by kylemacfarlane** [comment]
I don't know enough about EXIF to say what should be done.

What seems to have happened with this file is it was originally a photo with ifd0 and included a thumbnail of the photo with ifd1. The photo was edited which meant ifd0 was dropped but the thumbnail is still the original unedited photo with ifd1.

So whatever app created the image plus everything I tried viewing it in (Chrome, Photoshop, Illustrator, Firefox, Inkscape, Edge, etc) seem to only obey ifd0 for the main image.

**Comment by jcupitt** [comment]
OK, it's always ifd0 in 8.6. Thanks for reporting this.
