### ISSUE TITLE
vips dzsave to .dzi does not produce expected tiles

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#795]
When producing a .dzi file and associated files with `vips dzsave`, sometimes the tile set produced does not have the tiles that the OpenSeadragon viewer expects to be there. 

vips-8.5.9

For instance, this .dzi and tiles, which were produced with `vips dzsave`, and are hosted on S3:

https://s3.amazonaws.com/chf-dzi-staging/02870w476%252Ffiles%252F6b7ae965-2a62-42ad-9d3d-1bdc01800c6f_checksumd1df3171134f5fd3f265b5dafb624206349fc171.dzi

OpenSeadragon is trying to request tiles that don't actually exist. Like a 10/4_0.jpg and 10/4_1.jpg, when the 10 subdir only goes up to `3_*`, not `4_*`. Or similarly, a 9/2_0.jpg and 9/2_1.jpg, when the 9 subdir only goes up to `1_*`.

The image appears to display fine, but presumably isn't quite as high resolution as OSD expects. Not sure if you could actually produce a distorted or incorrect image at certain pan/zooms, I don't entirely understand how the dzi format works. And the errors in console/screen are of course problematic. 

The OSD maintainer suspects it's a problem with `vips dzsave` generation, perhaps a rounding error in determining what tiles need to be produced. 

See: https://github.com/openseadragon/openseadragon/issues/1337

And: 

https://github.com/openseadragon/openseadragon/issues/1287

**Comment by jcupitt** [comment]
Looking at the output, for layer 9 (305 x 255), I see:

```
john@kiwi:~/pics/x_files$ vipsheader 9/*
9/0_0.jpeg: 255x255 uchar, 3 bands, srgb, jpegload
9/1_0.jpeg: 52x255 uchar, 3 bands, srgb, jpegload
```

ie. two tiles, with a single row 255 pixels high, and 255 + 52 - 2 = 305 pixels across.

You'd think it should be 256 pixels across to play nicely with jpeg 8x8 DCT blocks, but the idea is that with the 1 pixel overlap it can then fit within a power of two tile on the client. I think. I still get confused by this.

@iangilman, could I ping you for advice on this issue? How should the layers be laid out in this example?

**Comment by jrochkind** [comment]
Yeah, I don't personally understand how dzi tile calculation works -- one would think there would be an official standard 'right' way to do it, but the dzi 'standard' seems somewhat underdocumented, I think it's maybe just whatever Seadragon did maybe? Unfortunate. 

@jcupitt and @iangilman , hopefully you can work it out?

**Comment by iangilman** [comment]
Indeed... It's a shame we don't have details better documented! Maybe this is something we should add to the OSD wiki or something.

At any rate, the source of truth for how OSD handles it is:

https://github.com/openseadragon/openseadragon/blob/master/src/dzitilesource.js

In particular, `tileExists` is what determines whether a specific tile should exist or not.

It might also be interesting to look at deepzoom.py:

https://github.com/openzoom/deepzoom.py/blob/develop/deepzoom.py

...which was written by @gasi, one of the Seadragon developers, back in 2009. It produces tiles in the way OSD expects, I believe.

For that matter, @gasi might have some more definitive words on how things should be done. @gasi, would any of [these posts](https://www.gasi.ch/blog/) shed any light? Would you be up for helping write a definitive thing on these kinds of implementation details?

**Comment by jcupitt** [comment]
`deepzoom.py` outputs an extra row of tiles:

```
john@kiwi:~/pics/y/z_files$ vipsheader 9/*
9/0_0.jpg: 255x255 uchar, 3 bands, srgb, jpegload
9/0_1.jpg: 255x2 uchar, 3 bands, srgb, jpegload
9/1_0.jpg: 52x255 uchar, 3 bands, srgb, jpegload
9/1_1.jpg: 52x2 uchar, 3 bands, srgb, jpegload
```

Even though the extra row has no new pixels -- it just repeats the last two lines from the first row.

I'll see if it's easy to make `dzsave` do this as well.

**Comment by jrochkind** [comment]
Ah interesting, so the 'missing' tiles for my sample image probably don't actually have any pixels not present elsewhere? I guess that explains why I could see no problems with viewing, despite the http 404 on tile fetches!  

Still would def be nice to have these fetch errors.

**Comment by iangilman** [comment]
FWIW, I've made a start on a wiki page for documenting the format:

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

I realize it doesn't cover the nuances of rounding and such things, but we've got to start somewhere...

**Comment by jcupitt** [comment]
It looks like it's not trivial to generate the extra tiles. I'm inclined to just leave them out, since the 404 errors appear to be harmless.

I don't know what could be causing the blurry tiles. What if you copy extra tiles over from a deepzoom.py pyramid, does that fix it?

@iangilman, nice! I added some notes on overlap, tile size and rounding, hopefully I have it right.

**Comment by jcupitt** [comment]
... it's confusing expressed in text form. A diagram would be useful.

**Comment by jrochkind** [comment]
The 404 errors are _relatively_ harmless, but in default OSD, you get text in the background of the canvas reporting the error, which is annoying and an unprofessional presentation. 

Also, in a non-default configuration, you might want to capture and report tile loading errors in different ways (report either to users or to site maintainers), and of course these will be false positives. 

It's not the end of the world, but it is annoying.  But vips ability to create the DZI tile set from even very large inputs impressively quickly is also very valuable. 

Perhaps the 'legacy' deep zoom/DZI format is just showing it's age, and is not the best choice anymore. But I'm not sure if there's anything analagous available that is better. Can vips produce any other 'create all the tiles in advance' formats that OSD can read?

**Comment by jrochkind** [comment]
I don't follow the math myself at the moment. But if it's true, as has been suggested, that in all of these edge cases where OSD and vips disagree, the 'missing' tiles are duplicate pixel information which are actually unneeded -- perhaps OSD should actually be the one to change it's behavior, to not fetch these 'extra' tiles?  @iangilman it seems like you are the custodian of the DZI standard as it were, and could simply decide this is how it should be. Would it cause problems for anyone?  What do you think?

**Comment by iangilman** [comment]
@jcupitt Thank you for the additions on the wiki page... They look good to me. I agree a diagram would be helpful! The MSDN page has https://i-msdn.sec.s-msft.com/dynimg/IC141135.png but it's not that great.

As for the issue here, I think I've gotten to the bottom of it. I reproduced the image configuration mentioned in https://github.com/openseadragon/openseadragon/issues/1287:

* width: 4875
* height: 4071
* tileSize: 254
* overlap: 1

...and tiled it with VIPS and another older tool (just something I have lying around, but it is consistent with the other tools I'm aware of). The discrepancy between the two is on the vertical dimension. On level 9, VIPS produces a single tile high with a height of 255. The other tool produces two tiles high: one of 255 and the other of 2px.

The difference has to do with how the overlap is handled. Since the height of the image is 255, it can't be a single tile, since the tile size is 254. Therefore, if you don't take the overlap into account, you'll have one tile of 254 and another tile of 1. Then you add the overlap to the top tile, bumping it up to 255, and add the overlap to the bottom tile, bumping it up to 2.

Evidently VIPS is looking at the top tile and saying "well, with the addition of the overlap you actually have all of the pixels, so I don't need to bother with the second tile". While technically true, it confuses OSD, because a tile of 255 with this configuration means there must be another tile coming... otherwise it would just be 254.

While the way VIPS is doing it is a slight optimization, it also complicates the rules, and it's different from how OSD and all the other DZI creation tools I know of are doing it, so I think it's worth modifying VIPS to match the others in this case.

@jcupitt Now that I've figured out the source of the issue, does that shed some light on how to fix it in VIPS?

**Comment by jrochkind** [comment]
Does the overlap actually... matter? Do we need overlap at all? Can I tell vips to produce dzi tiles with no overlap, and then get consistent behavior? It looks like there is such an option. @iangilman , are there negative consequences at display for having no overlap?

I would rather vips just produced consistent tiles with the rest of the DZI universe, but @jcupitt said it was not trivial and [suggested an inclination](https://github.com/jcupitt/libvips/issues/795#issuecomment-344273426) to not do so. Perhaps he will change his inclination. But otherwise, if setting 0 overlap forces vips to create the same tiles OSD expects without weird edge cases....

**Comment by gasi** [comment]
Hello friends! I read through the issue and here are some thoughts / observations:

> @jrochkind: Does the overlap actually... matter? Do we need overlap at all?

Yes, overlap matters because browsers / rendering engines will sometimes show seams between adjacent images with no overlap due to floating point / rounding issues. See: http://benvanik.tumblr.com/post/13978156533/tile-overlap

> @jrochkind: Can I tell vips to produce dzi tiles with no overlap, and then get consistent behavior? It looks like there is such an option. @iangilman , are there negative consequences at display for having no overlap?

Yes, you can but you might see seams on certain zoom scales. See: http://benvanik.tumblr.com/post/13978156533/tile-overlap

> @jcupitt: ... it's confusing expressed in text form. A diagram would be useful.

Maybe these might help 😄 http://www.gasi.ch/blog/inside-deep-zoom-2

> @jcupitt: It looks like it's not trivial to generate the extra tiles. I'm inclined to just leave them out, since the 404 errors appear to be harmless.
> @iangilman: While the way VIPS is doing it is a slight optimization, it also complicates the rules, and it's different from how OSD and all the other DZI creation tools I know of are doing it, so I think it's worth modifying VIPS to match the others in this case.

While I don’t have full appreciation of the complexity to implement this in VIPS, I’d vote with @iangilman on making it consistent with all the other generation tools as well as viewers. Plus, 404s are unfortunate 😜 

While DZI may have its shortcomings, it is fairly commonplace in the already small zooming community, so I’d prefer not to splinter it even more with non-conforming implementations 😄 

## References

In terms of documentation of DZI, I recently resurrected my blog which has my notes of reverse-engineering the DZI file format for a Flash renderer back from 2008. Feel free to reuse any prose or images with attribution:

- http://www.gasi.ch/blog/inside-deep-zoom-1
- http://www.gasi.ch/blog/inside-deep-zoom-2
- http://www.gasi.ch/blog/inside-deep-zoom-3

@benvanik also has a great many blog posts on zooming, image pyramids, tile overlaps, and rendering:

- **Category:** http://benvanik.tumblr.com/tagged/zooming
- http://benvanik.tumblr.com/post/13883153608/high-res-zooming-images-are-easy
- http://benvanik.tumblr.com/post/13931208153/deepzoomseadragon-and-image-pyramids
- http://benvanik.tumblr.com/post/13941606764/tile-sizes
- http://benvanik.tumblr.com/post/13978156533/tile-overlap
- http://benvanik.tumblr.com/post/14027494017/temporal-blending-animation-is-an-art
- http://benvanik.tumblr.com/post/14079110659/spatial-blending-keeping-it-smooth
- http://benvanik.tumblr.com/post/14127398599/spatial-blending-softening-the-edges
- http://benvanik.tumblr.com/post/14176690650/clipping-and-lod-in-2d
- http://benvanik.tumblr.com/post/14222411302/drawing-an-image-pyramid
- http://benvanik.tumblr.com/post/14225281899/simple-image-pyramid-demo-in-500-lines-of

**Comment by jcupitt** [comment]
OK, let's tag this as a bug and I'll have a stab at it.

**Comment by iangilman** [comment]
@jcupitt Great! Thank you, and let me know if you need anything.

@gasi Thank you for that wealth of info! I'll add those links to the wiki...

**Comment by jcupitt** [comment]
Sorry for the delay, I've been distracted.

I've had a go at a patch for this issue. It seems to work, at least in this case. Some testing by someone other than me would be great!

**Comment by jcupitt** [comment]
@gasi, thank you very much for the nice writeup!

**Comment by iangilman** [comment]
@jcupitt Great! Where's the patch? How should we test?

**Comment by jcupitt** [comment]
Hello Ian, there's a branch linked from the commit above:

https://github.com/jcupitt/libvips/tree/add-extra-dzsave-tiles

Though the change itself is not very complex:

https://github.com/jcupitt/libvips/compare/add-extra-dzsave-tiles

**Comment by jcupitt** [comment]
Oh, to test, just see if it generates the extra row and column of tiles along the bottom and right when it should.

**Comment by iangilman** [comment]
@jcupitt The code looks good to me. I'd love to test it running, but it might be a bit of work for me to be able to build the project... I've started following the instructions under "Building libvips from git" in the Readme, and I've cloned the project and done the brew install, but the `./autogen.sh` is giving me these errors: 

```
./autogen.sh: line 37: aclocal: command not found
testing for glibtoolize ... using libtoolize
./autogen.sh: line 61: aclocal: command not found
./autogen.sh: line 62: autoconf: command not found
./autogen.sh: line 63: autoheader: command not found
./autogen.sh: line 64: libtoolize: command not found
./autogen.sh: line 65: automake: command not found
./autogen.sh: line 72: ./configure: No such file or directory
```

Let me know if you want to help me build. We can chat via Gitter, for instance, or continue going back and forth here in the issue.

At any rate, here's the test image I have: 

![tester](https://user-images.githubusercontent.com/338989/33336077-ae816278-d423-11e7-9789-522ebad67fab.jpg)

If you convert that with tile size 254 and overlap 1, level 9 should be 2 tiles tall and wide and level 10 should be 3 tiles tall and wide. The unpatched VIPS does 1x1 for level 9 and 2x2 for level 10 with that image.

**Comment by jcupitt** [comment]
Hello Ian, your test image seems to work for me with this patch.

You need to set your machine up for C development, perhaps it's not worth doing just for this one task. Let's merge this and people can test it in the beta. 

Well done to all of us for sorting this out!

**Comment by iangilman** [comment]
Sounds fair... And yes, quite the group effort to get to the bottom of it! Thank you for seeing it through :)

**Comment by jrochkind** [comment]
You all are my heroes, thank you!

**Comment by gasi** [comment]
Well done, @jcupitt & @iangilman! Excited to integrate this with ZoomHub at some point 😄

**Comment by jrochkind** [comment]
Hi, in what version of vips should I expect `dzsave` to be creating all the tiles OpenSeadragon expected?

I'm getting some missing tiles again, and before trying to investigate I want to make sure I have a recent enough vips to theoretically include the "fix" to agree with OSD about expected tiles.

**Comment by jcupitt** [comment]
It looks like 8.6 from Dec 2017 should include this improvement.

There was a more recent bug caused by a cairo regression -- it made tiles disappear from openslide images. Could that perhaps be causing your problems?

**Comment by jcupitt** [comment]
After looking at the linked issue, like this is probably a different problem.

@jrochkind could you open a new issue with a test image please.

**Comment by jrochkind** [comment]
OK thanks. I don't know what an "openslide image" is, so it's probably not that. 

I can try to open a new issue next week, if I can find time to reproduce. 

Actually guess what -- my relevant machine has vips `8.5.8` installed, which is less than 8.6, so that may be the whole issue right there, so thanks for giving version info! I will have to upgrade vips and see if I can still reproduce. 

(Not sure why it's winding up with such an old vips, but probably has to do with conservative distros and such).

**Comment by ChrisHSandN** [comment]
**I know this bug is very old (and long ago fixed)** but I find myself maintaining many historic deepzoom files processed before the fix (and I doubt I am alone) so I thought I would share my research into the side effects this caused:

* If any layer in the pyramid has a height of exactly (tile_size + 1) or (tile_size + 2) it will be missing the last tile strip of images.
* The issue did not occur for tiles in the horizontal direction (e.g. from different width inputs) as VIPS works in full width strips from the top to bottom so always wrote the full set of tiles across.
* (tile_size + 1) are effectively redundant as the strip above will contain the pixel as part of its bottom overlap.
* (tile_size + 2) tiles unfortunately result in the very bottom line of pixels being lost.

### Example at highest pyramid layer: (using default tile-size=256, tile-overlap=1):

| Input Image (layer 9)  | Output File(s) [v8.5.9] | Comment |
| ------------- | ------------- | ------------- |
| 100x255 | `9/0_0.jpeg` |  correct |
| 100x256 |  `9/0_0.jpeg` | correct |
| 100x257 |  `9/0_0.jpeg` | incorrect missing 2px `0_1.jpeg` |
| 100x258 |  `9/0_0.jpeg` | incorrect missing 3px `0_1.jpeg` |
| 100x259  |  `9/0_0.jpeg`  `9/0_1.jpeg` | correct |

### Example in a secondary layer:

| Input Image (layer 10)  | Pyramid (layer 9) | Output File(s) [v8.5.9] | Comment |
| ------------- | ------------- | ------------- | ------------- |
| 100x510 | 50x255 | `9/0_0.jpeg` | correct |
| 100x514 | 50x256 | `9/0_0.jpeg` | incorrect missing 2px `0_1.jpeg` |
| 100x516 | 50x257 | `9/0_0.jpeg` | incorrect missing 3px `0_1.jpeg` |
| 100x518 | 50x258 | `9/0_0.jpeg`  `9/0_1.jpeg` | correct |

*** 
I wrote a quick script to calculate all input heights and corresponding layers with missing tiles: https://jsfiddle.net/chris_h/36Lu48np/

e.g. for heights of 256-1000px the following input height + layer will be affected:
```
"height:", 257, "level:", 9, "topLevel:", true, "lostPixel:", false
"height:", 258, "level:", 9, "topLevel:", true, "lostPixel:", true
"height:", 513, "level:", 10, "topLevel:", true, "lostPixel:", false
"height:", 513, "level:", 9, "topLevel:", false, "lostPixel:", false
"height:", 514, "level:", 10, "topLevel:", true, "lostPixel:", true
"height:", 514, "level:", 9, "topLevel:", false, "lostPixel:", false
"height:", 515, "level:", 9, "topLevel:", false, "lostPixel:", true
"height:", 516, "level:", 9, "topLevel:", false, "lostPixel:", true
"height:", 769, "level:", 10, "topLevel:", true, "lostPixel:", false
"height:", 770, "level:", 10, "topLevel:", true, "lostPixel:", true
```

**Comment by iangilman** [comment]
@Chrishsandn thank you for sharing what you've found! No doubt it will be helpful for others in the same situation :-)
