### ISSUE TITLE
Error when writing to file

### ISSUE THREAD

**Issue by jtorresfabra** [jcupitt/libvips#849]
Hi I have a very simple piece of code that fails when I try to write the same image twice
```
// 1. read input image
vips::VImage src = vips::VImage::new_from_file( optimization.input.c_str(),
                            vips::VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
// 2. Write image 
vips_image_write_to_file(src.get_image(), "hello1.jpg","Q", 80, NULL);
vips_image_write_to_file(src.get_image(), "hello2.jpg","Q", 90, NULL);
```
Then I get:

> VIPS-WARNING **: error in tile 0 x 0
> memory: high-water mark 15.86 MB
> error buffer: vipspng: out of order read at line 2048

and hello2.jpg is not correctly written

If I read the image twice then it does not happen like 

```      
 // 1. read input image
 vips::VImage src = vips::VImage::new_from_file( optimization.input.c_str(),
                            vips::VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
vips::VImage src1 = vips::VImage::new_from_file( optimization.input.c_str(),
                            vips::VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
// 2. Write image 
vips_image_write_to_file(src.get_image(), "hello1.jpg","Q", 80, NULL);
vips_image_write_to_file(src1.get_image(), "hello2.jpg","Q", 90, NULL);
```

Is this a expected fail? Am I missing something?

**Comment by jcupitt** [comment]
Hello @jtorresfabra, yes, this is expected behaviour.

If you open an image as `SEQUENTIAL`, it will be streamed through your computer. You must use the image only once, and you must use it in a way that works with top-to-bottom processing. 

You can leave off the `SEQUENTIAL` hint and use the image many times (and do non-top-to-bottom processing like a 90 degree rotate), or you can reopen the image every time you want to reuse it.

**Comment by jtorresfabra** [comment]
ok makes sense. thanks for your ultrafast response, as usual :)
