### ISSUE TITLE
vips_affine default background introduces unexpected alpha

### ISSUE THREAD

**Issue by pteichman** [jcupitt/libvips#860]
Using libvips 8.6.1, and maybe this is intended behavior. I just wanted to raise an issue since it was unexpected to me.

I'm resizing an image using vips_affine and only specifying hscale and vscale: a "pure" resize and not a full affine transform. The image has an alpha channel but is fully opaque.

With some combinations of scale, I'm getting pixels that are semitransparent at the edges of the scaled output. I haven't had a chance to dig into the code, but it feels like the "black" default of the new background parameter may be a fully transparent black: {0, 0, 0, 0}.

The unexpected behavior is introducing transparency where there was none before. It's easy enough to work around if this is intended.

**Comment by jcupitt** [comment]
Hello @pteichman,

Yes, there was a change in how edges were handled in affine: they should now have some transparency. This removes jaggies under rotation.

You shouldn't see them with just a resize though. Could you give a sample image and code to show the problem?

**Comment by pteichman** [comment]
@jcupitt Sure thing. I'm attaching two files:
* image-860.png: a 400x250 pure blue image
* image-860-out.png: the output of running the test program below

```#include <vips/vips.h>

int main(int argc, char **argv) {
    VipsImage *src = vips_image_new_from_file ("issue-860.png", NULL);
    VipsImage *dst;

    double hscale = 2.017500;
    double vscale = 2.016000;

    vips_affine(src, &dst, hscale, 0, 0, vscale, NULL);
    vips_image_write_to_file(dst, "issue-860-out.png", NULL);
}
```

The newly translucent pixels are visible here in MacOS Preview.app but you can also see the change in histogram with ImageMagick `identify -verbose issue-860.png issue-860-out.png`:

    image-860.png
      Colors: 1
      Histogram:
        100000: (  0,  0,204,255) #0000CCFF srgba(0,0,204,1)
    
    image-860-out.png
      Colors: 11
      Histogram:
         28736: (  0,  0,203,255) #0000CBFF srgba(0,0,203,1)
           722: (  0,  0,203,126) #0000CB7E srgba(0,0,203,0.494118)
           635: (  0,  0,203,252) #0000CBFC srgba(0,0,203,0.988235)
           397: (  0,  0,203,254) #0000CBFE srgba(0,0,203,0.996078)
        324435: (  0,  0,204,255) #0000CCFF srgba(0,0,204,1)
         50542: (  0,  0,204,254) #0000CCFE srgba(0,0,204,0.996078)
           672: (  0,  0,204,252) #0000CCFC srgba(0,0,204,0.988235)
           585: (  0,  0,204,126) #0000CC7E srgba(0,0,204,0.494118)
             2: (  0,  0,204,125) #0000CC7D srgba(0,0,204,0.490196)
             1: (  0,  0,204,250) #0000CCFA srgba(0,0,204,0.980392)
             1: (  0,  0,204, 62) #0000CC3E srgba(0,0,204,0.243137)

![issue-860](https://user-images.githubusercontent.com/69112/35240092-3541bdc6-ff67-11e7-9431-3a7d83d0481b.png)
![issue-860-out](https://user-images.githubusercontent.com/69112/35240095-35960e08-ff67-11e7-99a1-7a77bad5839b.png)

**Comment by jcupitt** [comment]
Oh dear, I see it here too:

```
$ vipsheader image-860.png 
image-860.png: 400x250 uchar, 3 bands, srgb, pngload
$ vips affine image-860.png x.png "2.017500 0 0 2.016000"
$ vips getpoint x.png 806 503
0 0 63 
```

I'll investigate. Thanks for reporting this!

**Comment by jcupitt** [comment]
I think it's actually working correctly -- this is a consequence of an improvement made to the way that affine handles edges. I would use the higher-level `resize` operator instead for upsizing:

```
$ vips resize image-860.png x.png 2.017500 --vscale 2.016000
```

should do what you want. 

The problem is clearer with a small image. Consider this 3x3 pixel test image (blown up to make it easy to see):

![x](https://user-images.githubusercontent.com/580843/35284401-9d33701e-0052-11e8-9193-68aa9a23665a.png)

If I run this:

```
$ vips affine 3x3.png x.png "100 0 0 100"
```

I see:

![x](https://user-images.githubusercontent.com/580843/35284459-c9f83d64-0052-11e8-96a3-fdd4d57a809f.png)

There are two points:

* `affine` is using corner convention. Corner convention means the value of a pixel is at the top left, not the centre. 
* It uses the background to make off-image data. The background is 0 by default, so you see black at the bottom and right. 

You can change both these. Use `idx` and `idy` to set an input delta in x and y. Use 0.5 to get centre (centre of pixel) convention. This:

```
$ vips affine 3x3.png x.png "100 0 0 100" --idx 0.5 --idy 0.5
```

Makes:

![x](https://user-images.githubusercontent.com/580843/35284696-667f0546-0053-11e8-9da8-b801a7d48cab.png)

Which is now symmetrical. 

Use `extend` to change the way new pixels are created. This has various settings, but the most useful is perhaps `copy`, where new pixels are made by copying edges outwards. This:

```
$ vips affine 3x3.png x.png "100 0 0 100" --idx 0.5 --idy 0.5 --extend copy
```

Makes:

![x](https://user-images.githubusercontent.com/580843/35284866-ca94b26a-0053-11e8-9910-ca92de20c54b.png)

That's with a bilinear interpolator. Bicubic looks a bit nicer:

```
$ vips affine 3x3.png x.png "100 0 0 100" --idx 0.5 --idy 0.5 --extend copy --interpolate bicubic
```

Making:

![x](https://user-images.githubusercontent.com/580843/35284956-052aa79a-0054-11e8-8034-48007008bd2d.png)

Phew!

**Comment by pteichman** [comment]
Sounds good to me, and thanks for the examples: that's also one of the better illustrations of center vs corner convention I've seen! I'll close this out.
