### ISSUE TITLE
LibVips segfault on image extend background

### ISSUE THREAD

**Issue by ryanjameslett** [jcupitt/libvips#865]
Hi there, this is a bit of a continuation regarding this post about maintaining a 1:1 aspect ratio using vips' extend functionality (https://github.com/jcupitt/libvips/issues/790#issuecomment-340568993).

I've been tasked with extending the go-based imageproxy (https://github.com/DarthSim/imgproxy) with an additional 'extend' resize option. I have it working using extend simply with a black background using the VIPS_EXTEND_BACKGROUND option, but when I attempt to use the VIPS_EXTEND_BACKGROUND option I get a segfault. Here's my modification of the vips.h file:

```
// failing version
int
vips_embed_go(VipsImage *in, VipsImage **out, int x, int y, int width, int height) {
    double bgarr[3] = {25.0, 25.0, 25.0};
    // the eventual goal is to pass the background array in as a parameter but I just want to get it
    // working at this point.
    return vips_embed(in, out,
            x, y,
            width, height,
            VIPS_EXTEND_BACKGROUND,
            bgarr,
            (char*)NULL);
}
```

```
// working version
int
vips_embed_go(VipsImage *in, VipsImage **out, int x, int y, int width, int height) {
    return vips_embed(in, out, x, y,
            width, height,
            VIPS_EXTEND_BLACK,
            (char*)NULL);
}
```
Full disclosure: it's been some time since I've written any C and this is my first foray into Go, so it's entirely possible that I'm doing something wrong here. It's also worth mentioning that I also tried using VIPS_EXTEND_COPY and VIPS_EXTEND_WHITE and those both resulted in similar-looking segfaults. I apologize in advance if this is related to the go project and I'm wasting your time.

Here's what appears to be a related section from the crashlog. Not sure if this is useful at all but fwiw:
```
goroutine 9 [syscall, locked to thread]:
runtime.cgocall(0x55e1fa58f0f0, 0xc420049890, 0x55e1fa330001)
	/usr/lib/go/src/runtime/cgocall.go:132 +0xea fp=0xc420049848 sp=0xc420049808 pc=0x55e1fa32ed2a
main._Cfunc_vips_embed_go(0x55e1fc35a320, 0xc42000e120, 0x7400000000, 0x1f400000190, 0x0)
	imgproxy/_obj/_cgo_gotypes.go:395 +0x4f fp=0xc420049890 sp=0xc420049848 pc=0x55e1fa587dff
main.vipsExtendImage.func1(0x55e1fc35a320, 0xc42000e120, 0x7400000000, 0x1f400000190, 0x55e100000000)
	/go/src/imgproxy/process.go:508 +0x109 fp=0xc4200498d0 sp=0xc420049890 pc=0x55e1fa58d4e9
main.vipsExtendImage(0xc42000e0f8, 0x190, 0x10b, 0x190, 0x1f4, 0x55e1fc35a190, 0x0)
	/go/src/imgproxy/process.go:508 +0xa0 fp=0xc420049910 sp=0xc4200498d0 pc=0x55e1fa58b090
main.processImage(0xc4201b0000, 0x11c93, 0x12eb9, 0x1, 0x3, 0x190, 0x1f4, 0x0, 0x1, 0x2, ...)
	/go/src/imgproxy/process.go:345 +0x640 fp=0xc4200499f0 sp=0xc420049910 pc=0x55e1fa589d10
main.(*httpHandler).ServeHTTP(0xc42000e0a8, 0x55e1fa9d5960, 0xc420128000, 0xc420124000)
	/go/src/imgproxy/server.go:200 +0x425 fp=0xc420049d18 sp=0xc4200499f0 pc=0x55e1fa586a05
net/http.serverHandler.ServeHTTP(0xc42006f1e0, 0x55e1fa9d5960, 0xc420128000, 0xc420124000)
	/usr/lib/go/src/net/http/server.go:2619 +0xb6 fp=0xc420049d48 sp=0xc420049d18 pc=0x55e1fa535f56
net/http.(*conn).serve(0xc420074780, 0x55e1fa9d5da0, 0xc420058300)
	/usr/lib/go/src/net/http/server.go:1801 +0x71f fp=0xc420049fc8 sp=0xc420049d48 pc=0x55e1fa532bcf
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420049fd0 sp=0xc420049fc8 pc=0x55e1fa386261
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2720 +0x28a
```

**Comment by jcupitt** [comment]
Hello @ryanjameslett, you're very close, you just need to pass an array object rather than a simple pointer to double, and you need to name your arguments. Something like (untested):

```C
VipsArrayDouble *array;
VipsImage *in = .... input image;
VipsImage *out;

array = vips_array_double_newv(3, r, g, b);
if (vips_embed(in, &out, x, y, w, h,
    "extend", VIPS_EXTEND_BACKGROUND,
    "background", array,
    NULL)) {
    error ...
}
vips_area_unref(VIPS_AREA(array));
```

So:

1. Extra optional arguments are passed as name / value pairs, terminated with `NULL`. You can see the names and types in the API docs: http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-embed
2. Array values are passed as array objects and must be unreffed when you're done with them. You'll need to check that the error path above ends up unreffing the array, for example.
3. The array you pass should have a single value (it'll be expanded to match the number of channels in the image), or it can have the same number of bands as the image (you can't pass three values for a four band image).
4. This will leave the number of refs on `in` unchanged, and return a new image via the `out` parameter with a single reference which you own. You'll need to make sure the two images get unreffed appropriately at some point with `g_object_unref()`.

**Comment by ryanjameslett** [comment]
Thanks so much. I'll give that a shot right now.

**Comment by ryanjameslett** [comment]
Awesome. I'm back on track now. Thanks so much for your help.
