### ISSUE TITLE
Determine jpeg quality

### ISSUE THREAD

**Issue by andrews05** [jcupitt/libvips#895]
Hi, I'm currently looking at moving to libvips from imagemagick. One thing I was doing in imagemagick which I would also like to achieve in libvips if possible, is recompressing a jpeg file if it exceeds a certain 'quality'. In imagemagick I was using `getImageCompressionQuality()` to do this. I know this is not an accurate reflection of the quality factor the jpeg would have been created with (in fact I'm not sure how it determines the quality at all) but it was sufficient for my needs.
Is there any way I can achieve something similar in libvips?

**Comment by jcupitt** [comment]
I think that IM method tries to guess the original Q factor from a quick examination of the Huffman tables on the file. I'm sorry, there's nothing similar in libvips. 

If you have access to the file, you could guess from the compression ratio. Look at the size of the file on disc and compare it to the uncompressed size: Q 75 is about 10:1, Q90 is about 5:1, I think.

**Comment by jcupitt** [comment]
I did a quick test and got:

Q100 = 5:1
Q90 = 15:1
Q75 = 20:1
Q50 = 30:1

**Comment by andrews05** [comment]
Okay, thanks for that, I'll give it a try. I was also considering comparing file size to pixel count.

**Comment by andrews05** [comment]
Is there any easy way to get the size of just the image data on disc, without all the profiles and other metadata? I've found profiles are majorly throwing out my compression ratio calculations.

**Comment by jcupitt** [comment]
You could subtract the size of the profile and other metadata. They are stored in the jpg file uncompressed, so I think you can just take them off.

In Ruby, something like:

```ruby
filename = "sample.jpg"
image = Vips::Image.new_from_file filename
disc_size = File.open(filename).size
uncompressed_size = image.width * image.height * image.bands

def optional_size(image, field)
    image.get_typeof field != 0 ? image.get(field).length : 0
end

compressed_size = disc_size - 
    optional_size(image, "xmp-data") -
    optional_size(image, "iptc-data") -
    optional_size(image, "icc-profile-data") -
    optional_size(image, "exif-data") 

compression_ratio = uncompressed_size.float / compressed_size
```

**Comment by andrews05** [comment]
Awesome, thanks heaps!

**Comment by maxence33** [comment]
Hi @jcupitt , @andrews05 
I am also interested in getting the Jpeg quality to avoid the versionning of low quality Jpeg into higher quality Jpeg. (I do some versionning through Shrine with Image_processing VIPS). For now I use ImageMagick in development through what I guess is IM -identify to get the quality..
But I am still in development so RAM is not a problem.. but once on Heroku it will be a different story.

I was wondering if VIPS was now supporting such feature ?
If it is not I will rely on your technique of determining the approximate quality with compressed and uncompressed sizes ratios. 
Also I was wondering is a table based on big samples exists somewhere so I can refine to a step of one 1 percent reliably ?
Otherwise I will prepare a sample of 50 metadata stripped 100% Jpegs that I will run into Shrine+Vips and will let Rails do the maths to make such table..

Otherwise I have read here and there that IM identify was relying on the Quantization tables (Huffman tables aformentioned?). There is this bit of code http://www.hackerfactor.com/src/jpegquality.c but it is from 2007 and don't even know what it is written in.
Do you have any idea if I can find something similar in Ruby that would be more speedy that calling IM in Shrine or it is just too much hassle and not especially better than my 50 samples table of Uncompressed/compressed ratios ?
