### ISSUE TITLE
still old version of libvips-tools in apt package

### ISSUE THREAD

**Issue by hbakhtiyor** [jcupitt/libvips#939]
@jcupitt can you update the package to latest?

```
sudo apt install libvips-tools
vips --version
vips-8.4.5-Wed Jan 18 12:36:44 UTC 2017
```

**Comment by jcupitt** [comment]
Debian packages only get bugfixes. You have to update to a newer Debian to get a newer version. 

There's a new Ubuntu LTS due in a couple of weeks which should have 8.6.something I think.

**Comment by hbakhtiyor** [comment]
why binary version not available? like https://github.com/ncw/rclone/releases

**Comment by jcupitt** [comment]
I don't make binaries (except for Windows) -- I leave distribution up to package maintainers. 

Debian's policy is never to update packages (except for security fixes and critical bugs) because they prioritize stability. If you want a system with up to date binaries, you need to pick a different linux. Alpine is a very popular rolling release system.

**Comment by hbakhtiyor** [comment]
thanks
